Repository kubernetes-sigs/cri-tools, pull requests merged in 2018-08, with the labels that each got.

#363 Fix crictl ps and crictl pods.
  cmd/crictl/container.go
  cmd/crictl/sandbox.go
Labels: cncf-cla: yes, lgtm, size/XS

#367 Set ldflags in hack/release.sh
  hack/release.sh
Labels: cncf-cla: yes, lgtm, size/XS

#361 show concise image info for crictl ps
  cmd/crictl/container.go
  cmd/crictl/image.go
  cmd/crictl/sandbox.go
  cmd/crictl/stats.go
  cmd/crictl/util.go
  vendor.conf
  vendor/github.com/opencontainers/go-digest/LICENSE
  vendor/github.com/opencontainers/go-digest/LICENSE.docs
  vendor/github.com/opencontainers/go-digest/README.md
  vendor/github.com/opencontainers/go-digest/algorithm.go
  vendor/github.com/opencontainers/go-digest/digest.go
  vendor/github.com/opencontainers/go-digest/digester.go
  vendor/github.com/opencontainers/go-digest/doc.go
  vendor/github.com/opencontainers/go-digest/verifiers.go
Labels: cncf-cla: yes, lgtm, size/XXL

#369 support to show podid in crictl ps
  cmd/crictl/container.go
Labels: cncf-cla: yes, lgtm, size/XS

#370 crictl: Fallback if info key is not JSON
  cmd/crictl/util.go
Labels: cncf-cla: yes, lgtm, size/XS

#372 vendor latest github.com/urfave/cli
  vendor.conf
  vendor/github.com/urfave/cli/command.go
Labels: cncf-cla: yes, lgtm, size/M
