Repository kubernetes-sigs/cri-tools, pull requests merged in 2018-09, with the labels that each got.

#376 Fix package paths after moving to kubernetes-sigs
  .travis.yml
  CHANGELOG.md
  Makefile
  README.md
  cmd/crictl/main.go
  cmd/critest/cri_test.go
  docs/benchmark.md
  docs/crictl.md
  docs/validation.md
  hack/release.sh
  pkg/benchmark/benchmark.go
  pkg/benchmark/container.go
  pkg/benchmark/image.go
  pkg/benchmark/pod.go
  pkg/validate/apparmor.go
  pkg/validate/container.go
  pkg/validate/container_linux.go
  pkg/validate/e2e.go
  pkg/validate/image.go
  pkg/validate/networking.go
  pkg/validate/pod.go
  pkg/validate/runtime_info.go
  pkg/validate/security_context.go
  pkg/validate/selinux_linux.go
  pkg/validate/streaming.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#375 Add sandbox config to `image pull`
  cmd/crictl/image.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#374 A few fixes to defaults on Windows.
  cmd/crictl/main.go
  cmd/crictl/main_unix.go
  cmd/crictl/main_windows.go
  docs/benchmark.md
  docs/crictl.md
  docs/validation.md
  pkg/framework/test_context.go
  vendor.conf
  vendor/github.com/Microsoft/go-winio/LICENSE
  vendor/github.com/Microsoft/go-winio/README.md
  vendor/github.com/Microsoft/go-winio/backup.go
  vendor/github.com/Microsoft/go-winio/ea.go
  vendor/github.com/Microsoft/go-winio/file.go
  vendor/github.com/Microsoft/go-winio/fileinfo.go
  vendor/github.com/Microsoft/go-winio/pipe.go
  vendor/github.com/Microsoft/go-winio/privilege.go
  vendor/github.com/Microsoft/go-winio/reparse.go
  vendor/github.com/Microsoft/go-winio/sd.go
  vendor/github.com/Microsoft/go-winio/syscall.go
  vendor/github.com/Microsoft/go-winio/zsyscall_windows.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#378 crictl inspecti fail to unmarshal
  cmd/crictl/image.go
  cmd/crictl/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#377 Add new test to critest for privileged container
  pkg/validate/selinux_linux.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#384 Fix grpc dial timeout
  cmd/crictl/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#385 Add docs for runtime handler
  docs/crictl.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#390 Add `--auth` support for `crictl pull`.
  cmd/crictl/image.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#389 Update docs for v1.12.0
  CHANGELOG.md
  README.md
  docs/benchmark.md
  docs/crictl.md
  docs/validation.md
Labels: approved, cncf-cla: yes, lgtm, size/M
