Repository kubernetes-sigs/cri-tools, pull requests merged in 2018-06, with the labels that each got.

#321 Update crictl docs and examples
  docs/crictl.md
  docs/examples/container-config.json
  docs/examples/container-config.yaml
  docs/examples/podsandbox-config.json
  docs/examples/podsandbox-config.yaml
Labels: cncf-cla: yes, lgtm, size/L

#319 Add SECURITY_CONTACTS file
  SECURITY_CONTACTS
Labels: cncf-cla: yes, lgtm, size/S

#323 Show sha256sum on releasing
  hack/release.sh
Labels: cncf-cla: yes, size/XS

#327 Bump cri-tools to v1.11.0
  CHANGELOG.md
  cmd/crictl/main.go
  cmd/critest/cri_test.go
Labels: cncf-cla: yes, lgtm, size/M

#333 adds id text to each command
  cmd/crictl/attach.go
  cmd/crictl/container.go
  cmd/crictl/exec.go
  cmd/crictl/image.go
  cmd/crictl/logs.go
  cmd/crictl/portforward.go
  cmd/crictl/sandbox.go
Labels: cncf-cla: yes, lgtm, size/S
