Repository kubernetes-sigs/cri-tools, pull requests merged in 2018-11, with the labels that each got.

#400 Update version to 1.0.0-beta.2 for release-1.10
  cmd/crictl/main.go
  cmd/critest/cri_test.go
Labels: approved, cncf-cla: yes, size/XS

#401 Update version to 1.0.0-alpha.1 for release-1.9
  cmd/crictl/main.go
  cmd/critest/main.go
Labels: approved, cncf-cla: yes, size/XS

#402 Update version matrix
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#404 crictl: add option to filter by container name in ps
  cmd/crictl/constants.go
  cmd/crictl/container.go
  cmd/crictl/sandbox.go
  cmd/crictl/util.go
  cmd/crictl/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#405 Add `runtime-handler` flag in critest.
  pkg/benchmark/pod.go
  pkg/framework/test_context.go
  pkg/framework/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#406 Use metadata to filter
  cmd/crictl/constants.go
  cmd/crictl/container.go
  cmd/crictl/sandbox.go
Labels: approved, cherrypick, cncf-cla: yes, lgtm, size/M

#407 crictl inspect: print annotations and labels for table output
  cmd/crictl/container.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#410 Add exec sync timeout test.
  hack/run-critest.sh
  pkg/validate/container.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#411 Fix readonly filesystem test.
  pkg/validate/security_context.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
