Repository kubernetes-sigs/cri-tools, pull requests merged in 2018-07, with the labels that each got.

#338 Cherrypick #332
  cmd/crictl/constants.go
  cmd/crictl/sandbox.go
  cmd/crictl/sandbox_test.go
  cmd/crictl/util.go
Labels: cncf-cla: yes, lgtm, size/L

#339 Set version based on git tags.
  Makefile
  cmd/crictl/main.go
  cmd/critest/cri_test.go
  pkg/version/version.go
Labels: cncf-cla: yes, lgtm, size/M

#342 Fix some description in the usage
  cmd/crictl/container.go
  cmd/crictl/sandbox.go
Labels: cncf-cla: yes, lgtm, size/XS

#341 Better support terminal
  cmd/crictl/attach.go
  cmd/crictl/exec.go
  vendor.conf
  vendor/github.com/docker/docker/pkg/term/ascii.go
  vendor/github.com/docker/docker/pkg/term/proxy.go
  vendor/github.com/docker/docker/pkg/term/tc.go
  vendor/github.com/docker/docker/pkg/term/tc_solaris_cgo.go
  vendor/github.com/docker/docker/pkg/term/term.go
  vendor/github.com/docker/docker/pkg/term/term_windows.go
  vendor/github.com/docker/docker/pkg/term/termios_bsd.go
  vendor/github.com/docker/docker/pkg/term/termios_linux.go
  vendor/github.com/docker/docker/pkg/term/windows/ansi_reader.go
  vendor/github.com/docker/docker/pkg/term/windows/ansi_writer.go
  vendor/github.com/docker/docker/pkg/term/windows/console.go
  vendor/github.com/docker/docker/pkg/term/windows/windows.go
  vendor/github.com/docker/docker/pkg/term/winsize.go
  vendor/github.com/docker/docker/pkg/term/winsize_solaris_cgo.go
  vendor/github.com/mitchellh/go-wordwrap/LICENSE.md
  vendor/github.com/mitchellh/go-wordwrap/README.md
  vendor/github.com/mitchellh/go-wordwrap/wordwrap.go
  vendor/k8s.io/kubernetes/pkg/kubectl/util/term/resize.go
  vendor/k8s.io/kubernetes/pkg/kubectl/util/term/resizeevents.go
  vendor/k8s.io/kubernetes/pkg/kubectl/util/term/resizeevents_windows.go
  vendor/k8s.io/kubernetes/pkg/kubectl/util/term/term.go
  vendor/k8s.io/kubernetes/pkg/kubectl/util/term/term_writer.go
  vendor/k8s.io/kubernetes/pkg/util/interrupt/interrupt.go
Labels: cncf-cla: yes, lgtm, size/XXL

#343 Cherrypick #341
  cmd/crictl/attach.go
  cmd/crictl/exec.go
  vendor.conf
  vendor/github.com/docker/docker/pkg/term/ascii.go
  vendor/github.com/docker/docker/pkg/term/proxy.go
  vendor/github.com/docker/docker/pkg/term/tc.go
  vendor/github.com/docker/docker/pkg/term/tc_solaris_cgo.go
  vendor/github.com/docker/docker/pkg/term/term.go
  vendor/github.com/docker/docker/pkg/term/term_windows.go
  vendor/github.com/docker/docker/pkg/term/termios_bsd.go
  vendor/github.com/docker/docker/pkg/term/termios_linux.go
  vendor/github.com/docker/docker/pkg/term/windows/ansi_reader.go
  vendor/github.com/docker/docker/pkg/term/windows/ansi_writer.go
  vendor/github.com/docker/docker/pkg/term/windows/console.go
  vendor/github.com/docker/docker/pkg/term/windows/windows.go
  vendor/github.com/docker/docker/pkg/term/winsize.go
  vendor/github.com/docker/docker/pkg/term/winsize_solaris_cgo.go
  vendor/github.com/mitchellh/go-wordwrap/LICENSE.md
  vendor/github.com/mitchellh/go-wordwrap/README.md
  vendor/github.com/mitchellh/go-wordwrap/wordwrap.go
  vendor/k8s.io/kubernetes/pkg/kubectl/util/term/resize.go
  vendor/k8s.io/kubernetes/pkg/kubectl/util/term/resizeevents.go
  vendor/k8s.io/kubernetes/pkg/kubectl/util/term/resizeevents_windows.go
  vendor/k8s.io/kubernetes/pkg/kubectl/util/term/term.go
  vendor/k8s.io/kubernetes/pkg/kubectl/util/term/term_writer.go
  vendor/k8s.io/kubernetes/pkg/util/interrupt/interrupt.go
Labels: cncf-cla: yes, lgtm, size/XXL

#344 Add changelog for v1.11.1.
  CHANGELOG.md
Labels: cncf-cla: yes, lgtm, size/S

#345 Add missing windows library.
  vendor.conf
  vendor/github.com/Azure/go-ansiterm/LICENSE
  vendor/github.com/Azure/go-ansiterm/README.md
  vendor/github.com/Azure/go-ansiterm/constants.go
  vendor/github.com/Azure/go-ansiterm/context.go
  vendor/github.com/Azure/go-ansiterm/csi_entry_state.go
  vendor/github.com/Azure/go-ansiterm/csi_param_state.go
  vendor/github.com/Azure/go-ansiterm/escape_intermediate_state.go
  vendor/github.com/Azure/go-ansiterm/escape_state.go
  vendor/github.com/Azure/go-ansiterm/event_handler.go
  vendor/github.com/Azure/go-ansiterm/ground_state.go
  vendor/github.com/Azure/go-ansiterm/osc_string_state.go
  vendor/github.com/Azure/go-ansiterm/parser.go
  vendor/github.com/Azure/go-ansiterm/parser_action_helpers.go
  vendor/github.com/Azure/go-ansiterm/parser_actions.go
  vendor/github.com/Azure/go-ansiterm/states.go
  vendor/github.com/Azure/go-ansiterm/utilities.go
  vendor/github.com/Azure/go-ansiterm/winterm/ansi.go
  vendor/github.com/Azure/go-ansiterm/winterm/api.go
  vendor/github.com/Azure/go-ansiterm/winterm/attr_translation.go
  vendor/github.com/Azure/go-ansiterm/winterm/cursor_helpers.go
  vendor/github.com/Azure/go-ansiterm/winterm/erase_helpers.go
  vendor/github.com/Azure/go-ansiterm/winterm/scroll_helper.go
  vendor/github.com/Azure/go-ansiterm/winterm/utilities.go
  vendor/github.com/Azure/go-ansiterm/winterm/win_event_handler.go
Labels: cncf-cla: yes, lgtm, size/XXL

#347 Add missing windows library.
  vendor.conf
  vendor/github.com/Azure/go-ansiterm/LICENSE
  vendor/github.com/Azure/go-ansiterm/README.md
  vendor/github.com/Azure/go-ansiterm/constants.go
  vendor/github.com/Azure/go-ansiterm/context.go
  vendor/github.com/Azure/go-ansiterm/csi_entry_state.go
  vendor/github.com/Azure/go-ansiterm/csi_param_state.go
  vendor/github.com/Azure/go-ansiterm/escape_intermediate_state.go
  vendor/github.com/Azure/go-ansiterm/escape_state.go
  vendor/github.com/Azure/go-ansiterm/event_handler.go
  vendor/github.com/Azure/go-ansiterm/ground_state.go
  vendor/github.com/Azure/go-ansiterm/osc_string_state.go
  vendor/github.com/Azure/go-ansiterm/parser.go
  vendor/github.com/Azure/go-ansiterm/parser_action_helpers.go
  vendor/github.com/Azure/go-ansiterm/parser_actions.go
  vendor/github.com/Azure/go-ansiterm/states.go
  vendor/github.com/Azure/go-ansiterm/utilities.go
  vendor/github.com/Azure/go-ansiterm/winterm/ansi.go
  vendor/github.com/Azure/go-ansiterm/winterm/api.go
  vendor/github.com/Azure/go-ansiterm/winterm/attr_translation.go
  vendor/github.com/Azure/go-ansiterm/winterm/cursor_helpers.go
  vendor/github.com/Azure/go-ansiterm/winterm/erase_helpers.go
  vendor/github.com/Azure/go-ansiterm/winterm/scroll_helper.go
  vendor/github.com/Azure/go-ansiterm/winterm/utilities.go
  vendor/github.com/Azure/go-ansiterm/winterm/win_event_handler.go
Labels: cncf-cla: yes, size/XXL

#346 Add cross build in travis.
  .travis.yml
Labels: cncf-cla: yes, lgtm, size/XS

#350 Add support to install kubelet from the corresponding branch.
  hack/install-kubelet.sh
Labels: cncf-cla: yes, lgtm, size/XS

#349 Cherrypick #339 to release-1.11.
  Makefile
  cmd/crictl/main.go
  cmd/critest/cri_test.go
  pkg/version/version.go
Labels: cherrypick, lgtm, size/M

#352 Cherrypick #350
  hack/install-kubelet.sh
Labels: cherrypick, lgtm, size/XS

#354 Properly returns errors when the output format is not supported
  cmd/crictl/container.go
  cmd/crictl/sandbox.go
Labels: cncf-cla: yes, lgtm, size/XS

#357 Update install guides and version info
  README.md
  docs/benchmark.md
  docs/crictl.md
  docs/validation.md
Labels: cncf-cla: yes, lgtm, size/M
