Repository kubernetes-sigs/cri-tools, pull requests merged in 2018-03, with the labels that each got.

#264 Allow combining of short boolean options.
  cmd/crictl/attach.go
  cmd/crictl/config.go
  cmd/crictl/container.go
  cmd/crictl/exec.go
  cmd/crictl/image.go
  cmd/crictl/info.go
  cmd/crictl/logs.go
  cmd/crictl/sandbox.go
  cmd/crictl/stats.go
  cmd/critest/benchmark.go
  vendor.conf
  vendor/github.com/urfave/cli/README.md
  vendor/github.com/urfave/cli/app.go
  vendor/github.com/urfave/cli/category.go
  vendor/github.com/urfave/cli/command.go
  vendor/github.com/urfave/cli/context.go
  vendor/github.com/urfave/cli/flag.go
  vendor/github.com/urfave/cli/flag_generated.go
  vendor/github.com/urfave/cli/funcs.go
  vendor/github.com/urfave/cli/help.go
  vendor/github.com/urfave/cli/sort.go
Labels: cncf-cla: yes, lgtm, size/XL

#267 critest: Add test for pid namespace and exec
  pkg/validate/security_context.go
Labels: cncf-cla: yes, lgtm, size/M

#268 Avoid panic when runtimes are using truncated IDs
  cmd/crictl/container.go
  cmd/crictl/image.go
  cmd/crictl/sandbox.go
  cmd/crictl/stats.go
Labels: cncf-cla: yes, lgtm, size/S

#261 critest: remove dependency of source code
  Makefile
  cmd/critest/benchmark.go
  cmd/critest/cri_test.go
  cmd/critest/main.go
  cmd/critest/util.go
  cmd/critest/validation.go
  docs/benchmark.md
  docs/validation.md
  hack/run-critest.sh
  pkg/benchmark/benchmark.go
  pkg/benchmark/image.go
  pkg/framework/test_context.go
  pkg/validate/e2e.go
Labels: cncf-cla: yes, lgtm, size/L

#270 CONTAINER_CREATED is not shown by plain crictl ps.
  docs/crictl.md
Labels: cncf-cla: yes, lgtm, size/XS

#272 Revert "Allow combining of short boolean options (e.g. crictl ps -aq)."
  cmd/crictl/attach.go
  cmd/crictl/config.go
  cmd/crictl/container.go
  cmd/crictl/exec.go
  cmd/crictl/image.go
  cmd/crictl/info.go
  cmd/crictl/logs.go
  cmd/crictl/sandbox.go
  cmd/crictl/stats.go
  vendor.conf
  vendor/github.com/urfave/cli/README.md
  vendor/github.com/urfave/cli/app.go
  vendor/github.com/urfave/cli/category.go
  vendor/github.com/urfave/cli/command.go
  vendor/github.com/urfave/cli/context.go
  vendor/github.com/urfave/cli/flag.go
  vendor/github.com/urfave/cli/flag_generated.go
  vendor/github.com/urfave/cli/funcs.go
  vendor/github.com/urfave/cli/help.go
  vendor/github.com/urfave/cli/sort.go
Labels: cncf-cla: yes, lgtm, size/XL

#271 Enable parallel tests
  Makefile
  cmd/critest/cri_test.go
  docs/validation.md
  hack/run-critest.sh
Labels: cncf-cla: yes, lgtm, size/M

#273 Fix parallel test.
  cmd/critest/cri_test.go
  pkg/framework/test_context.go
  pkg/framework/util.go
Labels: cncf-cla: yes, lgtm, size/M

#274 until there is an auth plan tls testing should support insecure
  cmd/crictl/attach.go
  cmd/crictl/exec.go
  pkg/validate/streaming.go
Labels: cncf-cla: yes, lgtm, size/S

#269 critest: Add test for exec
  pkg/validate/streaming.go
Labels: cncf-cla: yes, size/M

#276 Bump cri-tools to v1.0.0-beta.0
  CHANGELOG.md
  README.md
  cmd/crictl/main.go
  cmd/crictl/version.go
  cmd/critest/cri_test.go
Labels: cncf-cla: yes, lgtm, size/M

#278 Remove sandbox from user facing descriptions.
  cmd/crictl/container.go
  cmd/crictl/main.go
  cmd/crictl/portforward.go
  cmd/crictl/sandbox.go
  cmd/crictl/stats.go
Labels: cncf-cla: yes, lgtm, size/M

#279 oom_score_adj update is not supported.
  cmd/crictl/container.go
Labels: cncf-cla: yes, lgtm, size/XS
