Repository kubernetes-sigs/cri-tools, pull requests merged in 2018-05, with the labels that each got.

#296 Make crictl and critest statically linked.
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS

#298 Prepare for v1.0.0-beta.1 release.
  CHANGELOG.md
  README.md
  cmd/crictl/main.go
  cmd/critest/cri_test.go
Labels: cncf-cla: yes, lgtm, size/M

#301 Grammar in crictl output
  cmd/crictl/image.go
Labels: cncf-cla: yes, lgtm, size/XS

#306 crictl-exec: fix argument parsing
  cmd/crictl/attach.go
  cmd/crictl/config.go
  cmd/crictl/container.go
  cmd/crictl/exec.go
  cmd/crictl/image.go
  cmd/crictl/info.go
  cmd/crictl/logs.go
  cmd/crictl/sandbox.go
  cmd/crictl/stats.go
  vendor.conf
  vendor/github.com/urfave/cli/README.md
  vendor/github.com/urfave/cli/app.go
  vendor/github.com/urfave/cli/category.go
  vendor/github.com/urfave/cli/command.go
  vendor/github.com/urfave/cli/context.go
  vendor/github.com/urfave/cli/flag.go
  vendor/github.com/urfave/cli/flag_generated.go
  vendor/github.com/urfave/cli/funcs.go
  vendor/github.com/urfave/cli/help.go
  vendor/github.com/urfave/cli/sort.go
Labels: cncf-cla: yes, lgtm, size/XL

#295 Use kubelet 1.10.X for release-1.10 CI
  hack/install-kubelet.sh
Labels: cncf-cla: yes, lgtm, size/XS

#308 1.10 backports
  .travis.yml
  cmd/crictl/attach.go
  cmd/crictl/config.go
  cmd/crictl/container.go
  cmd/crictl/exec.go
  cmd/crictl/image.go
  cmd/crictl/info.go
  cmd/crictl/logs.go
  cmd/crictl/sandbox.go
  cmd/crictl/stats.go
  vendor.conf
  vendor/github.com/urfave/cli/README.md
  vendor/github.com/urfave/cli/app.go
  vendor/github.com/urfave/cli/category.go
  vendor/github.com/urfave/cli/command.go
  vendor/github.com/urfave/cli/context.go
  vendor/github.com/urfave/cli/flag.go
  vendor/github.com/urfave/cli/flag_generated.go
  vendor/github.com/urfave/cli/funcs.go
  vendor/github.com/urfave/cli/help.go
  vendor/github.com/urfave/cli/sort.go
Labels: cncf-cla: yes, lgtm, size/XL

#303 Add release scripts
  Makefile
  README.md
  hack/release.sh
Labels: cncf-cla: yes, lgtm, size/M

#312 Fixes a typo in inspecti usage
  cmd/crictl/image.go
Labels: cncf-cla: yes, size/XS

#311 Add push-manifest into all target in the image-user Makefile
  images/image-user/Makefile
Labels: cncf-cla: yes, lgtm, size/XS

#313 Make hostnet-nginx test images multi-arch
  images/hostnet-nginx/Dockerfile
  images/hostnet-nginx/Makefile
  images/hostnet-nginx/default.conf
Labels: cncf-cla: yes, lgtm, size/M

#315 Make image-test test images multi-arch
  images/image-test/Dockerfile
  images/image-test/Makefile
Labels: cncf-cla: yes, lgtm, size/M

#316 Cleanup container and sandbox state.
  cmd/crictl/container.go
  cmd/crictl/sandbox.go
Labels: cncf-cla: yes, lgtm, size/M
