Repository kubernetes-sigs/cri-tools, pull requests merged in 2018-02, with the labels that each got.

#240 Add version matrix
  README.md
Labels: cncf-cla: yes, lgtm, size/S

#244 Install kubelet 1.9 for release-1.9
  hack/install-kubelet.sh
Labels: cncf-cla: yes, size/XS

#247 Install kubelet 1.8 for release-1.8
  hack/install-kubelet.sh
Labels: size/XS

#248 Install kubelet 1.7 for release-1.7
  hack/install-kubelet.sh
  pkg/validate/image.go
Labels: cncf-cla: yes, size/S

#242 Add reopen container log test.
  hack/run-critest.sh
  pkg/validate/container.go
Labels: cncf-cla: yes, lgtm, size/M

#253 Fixed simple typos
  docs/crictl.md
Labels: cncf-cla: yes, lgtm, size/XS

#252 Improve image test and make test run in parallel.
  hack/run-critest.sh
  images/image-test/Dockerfile
  images/image-test/Makefile
  pkg/framework/util.go
  pkg/validate/image.go
  pkg/validate/networking.go
  pkg/validate/streaming.go
Labels: cncf-cla: yes, lgtm, size/L

#256 Add `crictl ps -q`.
  cmd/crictl/container.go
Labels: cncf-cla: yes, lgtm, size/XS

#257 Add golang 1.10 and fix a race condition.
  .travis.yml
  pkg/validate/streaming.go
Labels: cncf-cla: yes, lgtm, size/M

#250 pkg: validate: validate Username not empty in ImageStatus
  images/image-user/Dockerfile
  images/image-user/Makefile
  pkg/validate/image.go
Labels: cncf-cla: yes, lgtm, size/L

#258 Change CRI endpoints environment variable
  cmd/crictl/main.go
  cmd/critest/main.go
  docs/benchmark.md
  docs/crictl.md
  docs/validation.md
Labels: cncf-cla: yes, lgtm, size/S

#260 Add documentation about master version and branches
  README.md
Labels: cncf-cla: yes, lgtm, size/S
