Repository kubernetes-sigs/cri-tools, pull requests merged in 2018-10, with the labels that each got.

#391 Add multiple container in a pod test.
  pkg/validate/multi_container_linux.go
  pkg/validate/networking.go
  pkg/validate/streaming.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#393 Update versions
  .travis.yml
  README.md
  hack/repo-infra/verify/go-tools/verify-gometalinter.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#392 fix error way of parsing URL for cmd exec and attach
  cmd/crictl/attach.go
  cmd/crictl/exec.go
  cmd/crictl/portforward.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#394 Enable windows CI on travis
  .travis.yml
  hack/install-docker.sh
  hack/install-kubelet.ps1
Labels: approved, cncf-cla: yes, lgtm, sig/windows, size/M

#396 [release-1.9] Backport: fix a race condition
  pkg/validate/streaming.go
Labels: approved, cncf-cla: yes, lgtm, size/M
