Repository kubernetes-sigs/cri-tools, pull requests merged in 2019-05, with the labels that each got.

#462 Fix log directory typo in pod config examples.
  docs/crictl.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#463 Search program directory for config as fallback
  cmd/crictl/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#465 Update `rmp` to test for running sandbox
  cmd/crictl/sandbox.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#466 fix cannot set debug to false
  cmd/crictl/config.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#468 Test image status for various references.
  pkg/validate/image.go
Labels: approved, cncf-cla: yes, lgtm, size/S
