Repository kubernetes-sigs/cri-tools, pull requests merged in 2019-08, with the labels that each got.

#492 Add container 'run' command
  cmd/crictl/container.go
  cmd/crictl/main.go
  cmd/crictl/sandbox.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#493 Critest
  hack/install-docker.sh
  hack/run-critest.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#498 Travis ppc64le
  .travis.yml
  hack/install-docker.sh
  hack/run-critest.sh
  pkg/benchmark/image.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#495 Downgrade grpc-go to v1.17.0
  go.mod
  go.sum
  vendor/google.golang.org/grpc/.travis.yml
  vendor/google.golang.org/grpc/CONTRIBUTING.md
  vendor/google.golang.org/grpc/Makefile
  vendor/google.golang.org/grpc/README.md
  vendor/google.golang.org/grpc/backoff.go
  vendor/google.golang.org/grpc/balancer/balancer.go
  vendor/google.golang.org/grpc/balancer/base/balancer.go
  vendor/google.golang.org/grpc/balancer/roundrobin/roundrobin.go
  vendor/google.golang.org/grpc/balancer_conn_wrappers.go
  vendor/google.golang.org/grpc/balancer_v1_wrapper.go
  vendor/google.golang.org/grpc/call.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/codes/codes.go
  vendor/google.golang.org/grpc/connectivity/connectivity.go
  vendor/google.golang.org/grpc/credentials/credentials.go
  vendor/google.golang.org/grpc/credentials/tls13.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/encoding/encoding.go
  vendor/google.golang.org/grpc/go.mod
  vendor/google.golang.org/grpc/go.sum
  vendor/google.golang.org/grpc/grpclog/grpclog.go
  vendor/google.golang.org/grpc/internal/balancerload/load.go
  vendor/google.golang.org/grpc/internal/binarylog/env_config.go
  vendor/google.golang.org/grpc/internal/binarylog/method_logger.go
  vendor/google.golang.org/grpc/internal/channelz/funcs.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/syscall/syscall_nonlinux.go
  vendor/google.golang.org/grpc/internal/transport/handler_server.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/http_util.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/keepalive/keepalive.go
  vendor/google.golang.org/grpc/naming/dns_resolver.go
  vendor/google.golang.org/grpc/naming/naming.go
  vendor/google.golang.org/grpc/picker_wrapper.go
  vendor/google.golang.org/grpc/preloader.go
  vendor/google.golang.org/grpc/resolver/dns/dns_resolver.go
  vendor/google.golang.org/grpc/resolver/passthrough/passthrough.go
  vendor/google.golang.org/grpc/resolver/resolver.go
  vendor/google.golang.org/grpc/resolver_conn_wrapper.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/service_config.go
  vendor/google.golang.org/grpc/serviceconfig/serviceconfig.go
  vendor/google.golang.org/grpc/stats/stats.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/trace.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#496 Pull image on container creation
  cmd/crictl/container.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#500 Add documentation about 'run' command
  docs/crictl.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#501 Add saschagrunert to owners
  OWNERS
Labels: approved, cncf-cla: yes, do-not-merge/invalid-owners-file, size/XS

#502 Make runtime and image client non-global variables
  cmd/crictl/attach.go
  cmd/crictl/container.go
  cmd/crictl/exec.go
  cmd/crictl/image.go
  cmd/crictl/info.go
  cmd/crictl/logs.go
  cmd/crictl/portforward.go
  cmd/crictl/sandbox.go
  cmd/crictl/stats.go
  cmd/crictl/util.go
  cmd/crictl/version.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#503 Use a dedicated image for all reference test.
  hack/make-rules/Makefile.manifest
  images/hostnet-nginx/Makefile
  images/image-test-win/build.ps1
  images/image-test/Makefile
  images/image-user/Makefile
  pkg/validate/consts.go
  pkg/validate/image.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#505 Bump google.golang.org/grpc from 1.22.1 to 1.23.0
  go.mod
  go.sum
  vendor/google.golang.org/grpc/balancer.go
  vendor/google.golang.org/grpc/balancer/base/balancer.go
  vendor/google.golang.org/grpc/balancer_conn_wrappers.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/transport/controlbuf.go
  vendor/google.golang.org/grpc/internal/transport/flowcontrol.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/pickfirst.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XL

#506 Fix image build script for image test image.
  images/image-test/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#508 Update urfave/cli to v1.21.0
  go.mod
  go.sum
  vendor/github.com/urfave/cli/.travis.yml
  vendor/github.com/urfave/cli/CHANGELOG.md
  vendor/github.com/urfave/cli/MAINTAINERS.md
  vendor/github.com/urfave/cli/README.md
  vendor/github.com/urfave/cli/app.go
  vendor/github.com/urfave/cli/command.go
  vendor/github.com/urfave/cli/context.go
  vendor/github.com/urfave/cli/flag.go
  vendor/github.com/urfave/cli/flag_generated.go
  vendor/github.com/urfave/cli/generate-flag-types
  vendor/github.com/urfave/cli/go.mod
  vendor/github.com/urfave/cli/go.sum
  vendor/github.com/urfave/cli/help.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/L

#510 Enable deadcode, goimports, misspell and prealloc linters
  .golangci.yml
  cmd/crictl/logs.go
  cmd/crictl/util.go
  pkg/benchmark/image.go
  pkg/validate/apparmor.go
  pkg/validate/image.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#515 Disable ppc64le test.
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#517 The check should not have 1s timeout.
  pkg/validate/container.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#512 Treat first `crictl stats` argument as filter ID
  cmd/crictl/stats.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#513 Add -a (remove all) option to `rmp`
  cmd/crictl/sandbox.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#511 Add documentation about 'imagefsinfo' command
  docs/crictl.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#516 Create directory for config file.
  cmd/crictl/config.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#518 Fix dns test on windows.
  pkg/validate/apparmor_linux.go
  pkg/validate/consts.go
  pkg/validate/networking.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#519 Fix exec test on windows
  pkg/validate/streaming.go
Labels: approved, cncf-cla: yes, lgtm, size/M
