Repository kubernetes-sigs/cri-tools, pull requests merged in 2019-12, with the labels that each got.

#556 Print the previous log of the container(just like kubectl)
  cmd/crictl/logs.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#562 Bump cri-tools version in markdown docs
  README.md
  docs/benchmark.md
  docs/crictl.md
  docs/validation.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#563 Fix removal of container forcibly
  cmd/crictl/container.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#564 Update change log for v1.17.0
  CHANGELOG.md
Labels: approved, cncf-cla: yes, lgtm, size/L
