Repository kubernetes-sigs/cri-tools, pull requests merged in 2019-06, with the labels that each got.

#475 Skip test "image status should support all kinds of references" for docker runtime
  pkg/validate/image.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#467 support live monitoring critool stats
  cmd/crictl/container.go
  cmd/crictl/display.go
  cmd/crictl/image.go
  cmd/crictl/sandbox.go
  cmd/crictl/stats.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#471 Fallback to repo digest name if repoTag is <none>:<none>
  cmd/crictl/image.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#476 Fix typo in parallel
  cmd/critest/cri_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#478 Upgrade Kuberntes version to v1.15.0
  cmd/crictl/attach.go
  cmd/crictl/container.go
  cmd/crictl/exec.go
  cmd/crictl/image.go
  cmd/crictl/info.go
  cmd/crictl/main.go
  cmd/crictl/portforward.go
  cmd/crictl/sandbox.go
  cmd/crictl/stats.go
  cmd/crictl/util.go
  cmd/crictl/version.go
  pkg/benchmark/container.go
  pkg/benchmark/image.go
  pkg/benchmark/pod.go
  pkg/benchmark/pod_container.go
  pkg/framework/framework.go
  pkg/framework/util.go
  pkg/validate/apparmor.go
  pkg/validate/consts.go
  pkg/validate/container.go
  pkg/validate/container_linux.go
  pkg/validate/image.go
  pkg/validate/multi_container_linux.go
  pkg/validate/networking.go
  pkg/validate/pod.go
  pkg/validate/pod_linux.go
  pkg/validate/runtime_info.go
  pkg/validate/security_context_linux.go
  pkg/validate/selinux_linux.go
  pkg/validate/streaming.go
  vendor.conf
  vendor/k8s.io/cri-api/LICENSE
  vendor/k8s.io/cri-api/README.md
  vendor/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/api.pb.go
  vendor/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/api.proto
  vendor/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/constants.go
  vendor/k8s.io/cri-api/pkg/apis/services.go
  vendor/k8s.io/kubernetes/README.md
  vendor/k8s.io/kubernetes/pkg/kubectl/util/interrupt/interrupt.go
  vendor/k8s.io/kubernetes/pkg/kubectl/util/term/term.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/logs/logs.go
  vendor/k8s.io/kubernetes/pkg/kubelet/remote/remote_image.go
  vendor/k8s.io/kubernetes/pkg/kubelet/remote/remote_runtime.go
  vendor/k8s.io/kubernetes/pkg/kubelet/remote/utils.go
  vendor/k8s.io/kubernetes/pkg/kubelet/util/doc.go
  vendor/k8s.io/kubernetes/pkg/kubelet/util/logreduction/logreduction.go
  vendor/k8s.io/kubernetes/pkg/kubelet/util/util_unix.go
  vendor/k8s.io/kubernetes/pkg/kubelet/util/util_unsupported.go
  vendor/k8s.io/kubernetes/pkg/kubelet/util/util_windows.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#480 Revert "Skip test "image status should support all kinds of references" for docker runtime"
  pkg/validate/image.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
