Repository kubernetes-sigs/cri-tools, pull requests merged in 2019-09, with the labels that each got.

#520 Fix CRI test on windows.
  cmd/critest/cri_test.go
  pkg/validate/consts.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#524 Simplify Makefile.
  .travis.yml
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M

#525 Fix install on windows.
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#522 Add `images` aliases `image`, `img`
  cmd/crictl/image.go
  docs/crictl.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#521 Add container `rm` `--force, -f` and `--all, -a` flags
  cmd/crictl/container.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#523 Add `--all, -a` flag to image removal (`rmi`)
  cmd/crictl/image.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#526 Update ginkgo and gomega to the latest release
  go.mod
  go.sum
  vendor/github.com/onsi/ginkgo/CHANGELOG.md
  vendor/github.com/onsi/ginkgo/config/config.go
  vendor/github.com/onsi/ginkgo/ginkgo/bootstrap_command.go
  vendor/github.com/onsi/ginkgo/ginkgo/convert/import.go
  vendor/github.com/onsi/ginkgo/ginkgo/convert/package_rewriter.go
  vendor/github.com/onsi/ginkgo/ginkgo/convert/testfile_rewriter.go
  vendor/github.com/onsi/ginkgo/ginkgo/interrupthandler/interrupt_handler.go
  vendor/github.com/onsi/ginkgo/ginkgo/main.go
  vendor/github.com/onsi/ginkgo/ginkgo/suite_runner.go
  vendor/github.com/onsi/ginkgo/ginkgo/testrunner/test_runner.go
  vendor/github.com/onsi/ginkgo/ginkgo/watch/dependencies.go
  vendor/github.com/onsi/ginkgo/ginkgo/watch/package_hash.go
  vendor/github.com/onsi/ginkgo/ginkgo_dsl.go
  vendor/github.com/onsi/ginkgo/internal/codelocation/code_location.go
  vendor/github.com/onsi/ginkgo/internal/leafnodes/benchmarker.go
  vendor/github.com/onsi/ginkgo/internal/remote/aggregator.go
  vendor/github.com/onsi/ginkgo/internal/remote/server.go
  vendor/github.com/onsi/ginkgo/internal/spec/spec.go
  vendor/github.com/onsi/ginkgo/internal/spec/specs.go
  vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go
  vendor/github.com/onsi/ginkgo/reporters/default_reporter.go
  vendor/github.com/onsi/ginkgo/reporters/junit_reporter.go
  vendor/github.com/onsi/ginkgo/reporters/teamcity_reporter.go
  vendor/github.com/onsi/ginkgo/types/types.go
  vendor/github.com/onsi/gomega/.travis.yml
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/format/format.go
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/internal/asyncassertion/async_assertion.go
  vendor/github.com/onsi/gomega/matchers.go
  vendor/github.com/onsi/gomega/matchers/assignable_to_type_of_matcher.go
  vendor/github.com/onsi/gomega/matchers/be_a_directory.go
  vendor/github.com/onsi/gomega/matchers/be_a_regular_file.go
  vendor/github.com/onsi/gomega/matchers/be_an_existing_file.go
  vendor/github.com/onsi/gomega/matchers/be_closed_matcher.go
  vendor/github.com/onsi/gomega/matchers/be_element_of_matcher.go
  vendor/github.com/onsi/gomega/matchers/be_empty_matcher.go
  vendor/github.com/onsi/gomega/matchers/be_equivalent_to_matcher.go
  vendor/github.com/onsi/gomega/matchers/be_false_matcher.go
  vendor/github.com/onsi/gomega/matchers/be_identical_to.go
  vendor/github.com/onsi/gomega/matchers/be_nil_matcher.go
  vendor/github.com/onsi/gomega/matchers/be_numerically_matcher.go
  vendor/github.com/onsi/gomega/matchers/be_sent_matcher.go
  vendor/github.com/onsi/gomega/matchers/be_temporally_matcher.go
  vendor/github.com/onsi/gomega/matchers/be_true_matcher.go
  vendor/github.com/onsi/gomega/matchers/consist_of.go
  vendor/github.com/onsi/gomega/matchers/contain_element_matcher.go
  vendor/github.com/onsi/gomega/matchers/contain_substring_matcher.go
  vendor/github.com/onsi/gomega/matchers/have_cap_matcher.go
  vendor/github.com/onsi/gomega/matchers/have_key_matcher.go
  vendor/github.com/onsi/gomega/matchers/have_key_with_value_matcher.go
  vendor/github.com/onsi/gomega/matchers/have_occurred_matcher.go
  vendor/github.com/onsi/gomega/matchers/receive_matcher.go
  vendor/github.com/onsi/gomega/matchers/semi_structured_data_support.go
  vendor/github.com/onsi/gomega/matchers/support/goraph/bipartitegraph/bipartitegraph.go
  vendor/github.com/onsi/gomega/matchers/type_support.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/L

#527 Remove go module disabling
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#529 Add first crictl e2e test framework and suite
  .travis.yml
  Makefile
  test/e2e/help_test.go
  test/e2e/suite_test.go
  test/e2e/version_test.go
  test/framework/framework.go
  vendor/github.com/onsi/gomega/gbytes/buffer.go
  vendor/github.com/onsi/gomega/gbytes/io_wrappers.go
  vendor/github.com/onsi/gomega/gbytes/say_matcher.go
  vendor/github.com/onsi/gomega/gexec/build.go
  vendor/github.com/onsi/gomega/gexec/exit_matcher.go
  vendor/github.com/onsi/gomega/gexec/prefixed_writer.go
  vendor/github.com/onsi/gomega/gexec/session.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#530 Add `crictl info` e2e tests
  test/e2e/info_test.go
  test/framework/framework.go
  vendor/github.com/onsi/gomega/gbytes/say_matcher.go
  vendor/github.com/onsi/gomega/gexec/build.go
  vendor/github.com/onsi/gomega/gexec/exit_matcher.go
  vendor/github.com/onsi/gomega/gexec/prefixed_writer.go
  vendor/github.com/onsi/gomega/gexec/session.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#534 Add `crictl pull` e2e tests
  Makefile
  test/e2e/pull_test.go
  test/framework/framework.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#535 Update change log for v1.16.0
  CHANGELOG.md
  README.md
  docs/benchmark.md
  docs/crictl.md
  docs/validation.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#536 Avoid empty fields in crictl inspect(p/i) result.
  .travis.yml
  cmd/crictl/util.go
Labels: approved, cherrypick, cncf-cla: yes, lgtm, size/XS

#538 Skip running portforward on host network test for non-linux
  pkg/validate/streaming.go
  pkg/validate/streaming_linux.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#542 Add hostname test.
  pkg/validate/consts.go
  pkg/validate/container.go
  pkg/validate/networking.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#541 Pass pod config when pulling image during create
  cmd/crictl/container.go
  cmd/crictl/image.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#543 Fix crash when using stats command
  cmd/crictl/stats.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
