Repository kubernetes-sigs/cri-tools, pull requests merged in 2019-03, with the labels that each got.

#445 Fix docker installation for CI
  .travis.yml
  hack/install-docker.sh
  hack/run-critest.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#437 Add `-q` support for `crictl info`.
  cmd/crictl/info.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#434 update link to point to correct godep instructions
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#442 add simple completion support for zsh
  cmd/crictl/completion.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#447 Re-enable image bench tests
  .travis.yml
  hack/install-kubelet.sh
  hack/run-critest.sh
Labels: approved, cncf-cla: yes, size/S

#450 Upgrade go version to 1.12
  .travis.yml
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#452 Release version v1.14.0
  CHANGELOG.md
  README.md
  docs/benchmark.md
  docs/validation.md
  hack/release.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#456 Include gcs bucket release.
  hack/release.sh
Labels: approved, cncf-cla: yes, lgtm, size/S
