Repository kubernetes-sigs/cri-tools, pull requests merged in 2019-07, with the labels that each got.

#477 Add registry prefix option
  cmd/critest/cri_test.go
  pkg/framework/test_context.go
  pkg/framework/util.go
  vendor.conf
  vendor/github.com/docker/distribution/LICENSE
  vendor/github.com/docker/distribution/README.md
  vendor/github.com/docker/distribution/digestset/set.go
  vendor/github.com/docker/distribution/reference/helpers.go
  vendor/github.com/docker/distribution/reference/normalize.go
  vendor/github.com/docker/distribution/reference/reference.go
  vendor/github.com/docker/distribution/reference/regexp.go
  vendor/github.com/docker/distribution/vendor.conf
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#481 Update docs for cri-tools v1.15.0
  CHANGELOG.md
  README.md
  docs/benchmark.md
  docs/crictl.md
  docs/validation.md
Labels: approved, cncf-cla: yes, size/M

#484 make crictl CLI link more prominent on README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#483 clarify endpoints in crictl doc
  docs/crictl.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#485 link to related doc on crictl.md
  docs/crictl.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#487 Add test for MaskedPaths and ReadonlyPaths.
  hack/install-docker.sh
  pkg/validate/security_context_linux.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#488 Switch to multi-arch nonewprivs image.
  pkg/validate/security_context_linux.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#489 Use arch specific hostnet-nginx image.
  pkg/validate/consts.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
