Repository kubernetes-sigs/cri-tools, pull requests merged in 2020-08, with the labels that each got.

#646 Use Go 1.15-compatible ioutil.TempDir
  pkg/validate/container.go
  pkg/validate/container_linux.go
  pkg/validate/pod.go
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, size/XS

#647 Add runtime engines to containerd ci workflow
  .github/workflows/containerd.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#648 Add comment updates from PR #647
  .github/workflows/containerd.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#649 OWNERS: move euank to emeritus_approvers
  OWNERS
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#653 update readme.md with the latest version: v1.18.0
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/XS

#655 Makefile: use deferred assignment for BINDIR
  Makefile
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#656 move up to 1.4 release of containerd
  .github/workflows/containerd.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#658 Update PR template to reflect latest prow features
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M
