Repository kubernetes-sigs/cri-tools, pull requests merged in 2020-07, with the labels that each got.

#627 adds config and switches to manage pull-image for create/run commands
  cmd/crictl/config.go
  cmd/crictl/container.go
  cmd/crictl/main.go
  docs/crictl.md
  pkg/common/config.go
  pkg/common/file.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#611 Update dockershim critest
  .github/workflows/containerd.yml
  .github/workflows/dockershim.yml
  .travis.yml
  hack/install-cri-dockerd.sh
  hack/install-docker.sh
  hack/install-kubelet.ps1
  hack/install-kubelet.sh
  hack/run-dockershim-critest.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#633 add tests for remove container by force rule
  pkg/framework/util.go
  pkg/validate/container.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#637 fix containerd running critest on wrong commit and make default critest show version
  .github/workflows/containerd.yml
  cmd/critest/cri_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#638 use default fetch depth 1 for most checkouts
  .github/workflows/containerd.yml
  .github/workflows/crio.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#636 Add Kubernetes PR and issue template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M

#635 Remove Travis CI stages which are duplicated
  .github/workflows/build.yml
  .github/workflows/containerd.yml
  .github/workflows/crio.yml
  .github/workflows/dockershim.yml
  .github/workflows/e2e.yml
  .travis.yml
  hack/release.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#641 Replace containerd cri with just containerd
  .github/workflows/containerd.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L
