Repository kubernetes-sigs/cri-tools, pull requests merged in 2020-02, with the labels that each got.

#570 Fix invalid log_path in docs
  docs/crictl.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#566 Add container stats test
  pkg/validate/container.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#567 Cleanup container create test to reduce duplication
  pkg/validate/container.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#574 bugfix: start container before fetching metrics
  pkg/validate/container.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#575 cmd: add go-template option for inspect commands
  cmd/crictl/container.go
  cmd/crictl/image.go
  cmd/crictl/info.go
  cmd/crictl/sandbox.go
  cmd/crictl/templates.go
  cmd/crictl/templates_test.go
  cmd/crictl/util.go
  go.mod
  go.sum
  vendor/github.com/pkg/errors/.travis.yml
  vendor/github.com/pkg/errors/Makefile
  vendor/github.com/pkg/errors/README.md
  vendor/github.com/pkg/errors/errors.go
  vendor/github.com/pkg/errors/go113.go
  vendor/github.com/pkg/errors/stack.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/L
