Repository kubernetes-sigs/cri-tools, pull requests merged in 2020-05, with the labels that each got.

#595 Use errors.wrap instead of fmt.Errorf
  cmd/crictl/attach.go
  cmd/crictl/container.go
  cmd/crictl/exec.go
  cmd/crictl/image.go
  cmd/crictl/info.go
  cmd/crictl/portforward.go
  cmd/crictl/sandbox.go
  cmd/crictl/stats.go
  cmd/crictl/util.go
  cmd/crictl/version.go
  pkg/validate/apparmor_linux.go
  pkg/validate/security_context_linux.go
  test/e2e/pull_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#596 interrupt option for stats with watch
  cmd/crictl/stats.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#601 crictl: should allocate cap not len when append
  cmd/crictl/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#600 crictl: add Runtime column for RuntimeHandler
  cmd/crictl/display.go
  cmd/crictl/sandbox.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#599 Update the default CRI server
  cmd/crictl/main.go
  cmd/crictl/main_unix.go
  cmd/crictl/main_windows.go
  docs/crictl.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#603 Allow -s for --state when listing containers
  cmd/crictl/container.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#607 Fix e2e tests following docker changes in Kublet
  hack/install-kubelet.ps1
  hack/install-kubelet.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#604 Update set configuration command
  cmd/crictl/config.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#606 Fix server connection timeout
  cmd/crictl/main.go
  docs/crictl.md
  pkg/common/config.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#590 Update SELinux testing for MCS
  pkg/validate/selinux_linux.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#617 adds containerd github action tests
  .github/workflows/ci.yml
Labels: approved, cncf-cla: yes, lgtm, size/M
