Repository kubernetes-sigs/cri-tools, pull requests merged in 2020-11, with the labels that each got.

#667 docs: add getting started w/development guide
  docs/developer-guide.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M

#680 Update golangci-lint and fix issues
  .golangci.yml
  Makefile
  cmd/crictl/container.go
  cmd/crictl/sandbox.go
  cmd/crictl/util.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#682 pkg/validate/apparmor: fix path
  pkg/validate/apparmor_linux.go
Labels: approved, cncf-cla: yes, kind/bug, kind/failing-test, lgtm, size/XS

#683 crictl run: rm default 10s timeout
  cmd/crictl/container.go
Labels: approved, cncf-cla: yes, kind/bug, kind/regression, lgtm, size/XS

#685 Update actions/setup-go to v2
  .github/workflows/build.yml
  .github/workflows/containerd.yml
  .github/workflows/crio.yml
  .github/workflows/dockershim.yml
  .github/workflows/e2e.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#689 .github/workflows: fix GOROOT under sudo etc
  .github/workflows/containerd.yml
  .github/workflows/crio.yml
  .github/workflows/dockershim.yml
  .github/workflows/e2e.yml
Labels: approved, cncf-cla: yes, kind/bug, kind/failing-test, lgtm, size/M

#684 Makefile: assorted improvements
  Makefile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#691 .github/workflows: add go mod and build cache
  .github/workflows/build.yml
  .github/workflows/containerd.yml
  .github/workflows/crio.yml
  .github/workflows/dockershim.yml
  .github/workflows/e2e.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#692 ci/e2e: use latest runc release
  .github/workflows/e2e.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#695 version 1.17.0 -> 1.19.0 in crictl.md
  docs/crictl.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
