Repository kubernetes-sigs/cri-tools, pull requests merged in 2020-12, with the labels that each got.

#696 Add mechanism for building and pushing test user images to staging location
  images/image-user/Makefile
  images/image-user/cloudbuild-images.yaml
  images/image-user/cloudbuild-manifests.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#697 docs(*): Add clarity to docs about default runtimes
  docs/crictl.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#698 Add comment to cloud build manifest file
  images/image-user/cloudbuild-manifests.yaml
Labels: cncf-cla: yes, kind/documentation, lgtm, size/XS

#700 Fix(ci): CRI Test with Windows containerd runtime
  .github/workflows/containerd.yml
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, size/XS

#634 Dockershim critest on Windows
  .github/workflows/dockershim.yml
  images/image-user/cloudbuild-images.yaml
  images/image-user/cloudbuild-manifests.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#704 Trigger prow job
  images/image-user/Makefile
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, size/XS

#708 fix a bug in closure function
  cmd/crictl/sandbox.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S
