Repository kubernetes-sigs/cri-tools, pull requests merged in 2020-04, with the labels that each got.

#581 Use ContextDialer to fix build
  cmd/crictl/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#582 Update version matrix for v1.18
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#586 Add selinux build tag
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#583 Remove pod sandoxes in parallel
  cmd/crictl/sandbox.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#588 Add darwin to releases
  .travis.yml
  hack/release.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#591 critest: use os.Executable instead of exec.LookPath
  cmd/critest/cri_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#594 Enable critest to use CRI server configuration file
  cmd/crictl/config.go
  cmd/crictl/main.go
  cmd/critest/cri_test.go
  pkg/common/config.go
  pkg/common/file.go
  pkg/framework/test_context.go
Labels: approved, cncf-cla: yes, lgtm, size/L
