Repository kubernetes-sigs/cri-tools, pull requests merged in 2020-06, with the labels that each got.

#615 Make config write maintain comments
  cmd/crictl/config.go
  go.mod
  go.sum
  pkg/common/config.go
  pkg/common/file.go
  vendor/gopkg.in/yaml.v3/.travis.yml
  vendor/gopkg.in/yaml.v3/LICENSE
  vendor/gopkg.in/yaml.v3/NOTICE
  vendor/gopkg.in/yaml.v3/README.md
  vendor/gopkg.in/yaml.v3/apic.go
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/emitterc.go
  vendor/gopkg.in/yaml.v3/encode.go
  vendor/gopkg.in/yaml.v3/go.mod
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/gopkg.in/yaml.v3/readerc.go
  vendor/gopkg.in/yaml.v3/resolve.go
  vendor/gopkg.in/yaml.v3/scannerc.go
  vendor/gopkg.in/yaml.v3/sorter.go
  vendor/gopkg.in/yaml.v3/writerc.go
  vendor/gopkg.in/yaml.v3/yaml.go
  vendor/gopkg.in/yaml.v3/yamlh.go
  vendor/gopkg.in/yaml.v3/yamlprivateh.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#618 Use CRI-validation-friendly version of nginx image
  pkg/validate/security_context_linux.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#619 Add CRI-O critest GitHub action
  .github/workflows/ci.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#621 Add CRI-O GitHub action artifact
  .github/workflows/ci.yml
  pkg/validate/apparmor_linux.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#622 Add CRI-O v1.18.1 critest GitHub Action
  .github/workflows/ci.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#626 Exclude port forward test because of DNS issues
  .github/workflows/ci.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#623 feat(build): Add containerd v1.4.0 CRI CI test
  .github/workflows/containerd.yml
  .github/workflows/crio.yml
Labels: approved, cncf-cla: yes, lgtm, size/L

#630 Add multi-platform support for containerd cri ci test
  .github/workflows/containerd.yml
  .github/workflows/crio.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#624 Add waits for creations/modifications of timing-sensitive files
  pkg/validate/security_context_linux.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#631 Add remaining Travis CI stages to GitHub action workflow
  .github/workflows/build.yml
  .github/workflows/e2e.yml
Labels: approved, cncf-cla: yes, lgtm, size/L
