Repository kubernetes-sigs/cri-tools, pull requests merged in 2021-05, with the labels that each got.

#759 Mention deb/rpm packages hosted on OBS in README
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#763 Clone cri-dockerd from permanent repo
  .github/workflows/dockershim.yml
  hack/install-cri-dockerd.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#767 Update golangci-lint to v1.40.1 and fix lints
  .golangci.yml
  Makefile
  cmd/crictl/stats.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#720 Add global signal handler for Interrupt signal
  cmd/crictl/logs.go
  cmd/crictl/main_unix.go
  cmd/crictl/main_windows.go
  cmd/crictl/portforward.go
  cmd/crictl/stats.go
  cmd/crictl/util.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, sig/node, size/L
