Repository kubernetes-sigs/cri-tools, pull requests merged in 2021-06, with the labels that each got.

#782 rm_force_while_container_running_fix
  cmd/crictl/container.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#788 chore: switch containerd branch to main
  .github/workflows/containerd.yml
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, size/XS

#787 Update critest Windows tests.
  pkg/framework/util.go
  pkg/validate/consts.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#721 Update GitHub actions to go 1.16 and remove .travis.yml
  .github/workflows/build.yml
  .github/workflows/containerd.yml
  .github/workflows/crio.yml
  .github/workflows/e2e.yml
  .travis.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M
