Repository kubernetes-sigs/cri-tools, pull requests merged in 2021-01, with the labels that each got.

#711 Update CRI-O to v1.20.0
  .github/workflows/crio.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#714 Trigger prow job
  images/image-user/cloudbuild-images.yaml
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, ok-to-test, size/XS

#717 Modify hack/release.sh script to include sha256 sum files
  hack/release.sh
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M
