Repository kubernetes-sigs/cri-tools, pull requests merged in 2022-12, with the labels that each got.

#1030 add missing CPU count
  cmd/crictl/container.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#1043 set LTS v1.6.12 into matrix to replace old v1.5 entry
  .github/workflows/containerd.yml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1044 Add haircommander to reviewers
  OWNERS
Labels: cncf-cla: yes, lgtm, size/XS, kind/documentation, approved
