Repository kubernetes-sigs/cri-tools, pull requests merged in 2022-05, with the labels that each got.

#915 install CNI on linux
  .github/workflows/containerd.yml
Labels: cncf-cla: yes, lgtm, size/L, kind/failing-test, approved

#914 update containerd socket in windows
  cmd/crictl/main_windows.go
  docs/crictl.md
Labels: kind/bug, cncf-cla: yes, lgtm, size/XS, approved

#913 Fixes the incubator project reference
  README.md
Labels: cncf-cla: yes, lgtm, size/XS

#927 Use same grpc max message size as Kubelet
  cmd/crictl/main.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#931 Remove selinux build tag
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, kind/cleanup, approved

#930 cmd/critest: fix empty ginkgo flag's value issue
  cmd/critest/cri_test.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/M, approved

#935 docs: update the version to the latest
  README.md
  docs/crictl.md
Labels: cncf-cla: yes, lgtm, size/XS, kind/documentation, approved, ok-to-test

#894 Update container/pod benchmarking procedures.
  docs/benchmark.md
  pkg/benchmark/benchmark.go
  pkg/benchmark/container.go
  pkg/benchmark/image.go
  pkg/benchmark/pod.go
  pkg/benchmark/pod_container.go
  pkg/benchmark/util.go
  pkg/framework/test_context.go
  pkg/framework/util.go
  vendor/github.com/onsi/gomega/gmeasure/cache.go
  vendor/github.com/onsi/gomega/gmeasure/enum_support.go
  vendor/github.com/onsi/gomega/gmeasure/experiment.go
  vendor/github.com/onsi/gomega/gmeasure/measurement.go
  vendor/github.com/onsi/gomega/gmeasure/rank.go
  vendor/github.com/onsi/gomega/gmeasure/stats.go
  vendor/github.com/onsi/gomega/gmeasure/stopwatch.go
  vendor/github.com/onsi/gomega/gmeasure/table/table.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, size/XXL, kind/documentation, approved

#857 add tests for ListContainerStats
  .github/workflows/containerd.yml
  .github/workflows/dockershim.yml
  pkg/validate/container.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/M, approved

#940 Fix timeout for exec sync
  cmd/crictl/exec.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/XS, approved
