Repository kubernetes-sigs/cri-tools, pull requests merged in 2022-08, with the labels that each got.

#961 Bump version in install section to 1.24.2 on README
  README.md
Labels: cncf-cla: yes, lgtm, size/XS, kind/documentation, approved

#962 No truncate PodID in ps command if --no-trunc exists
  cmd/crictl/container.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/XS, approved

#938 Migrate to native ginkgo v2
  cmd/critest/cri_test.go
  pkg/benchmark/benchmark.go
  pkg/benchmark/pod_container.go
  pkg/validate/e2e.go
Labels: cncf-cla: yes, lgtm, size/L, kind/cleanup, approved

#969 cmd/crictl: replace deprecated pkg/term
  cmd/crictl/exec.go
  go.mod
  go.sum
  vendor/github.com/docker/docker/pkg/term/deprecated.go
  vendor/github.com/docker/docker/pkg/term/deprecated_unix.go
  vendor/github.com/moby/term/term_windows.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, size/L, kind/cleanup, approved
