Repository kubernetes-sigs/cri-tools, pull requests merged in 2022-01, with the labels that each got.

#855 Add support for specifying custom test container images.
  docs/validation.md
  pkg/framework/test_context.go
  pkg/framework/util.go
  pkg/validate/apparmor_linux.go
  pkg/validate/consts.go
  pkg/validate/container.go
  pkg/validate/container_linux.go
  pkg/validate/multi_container_linux.go
  pkg/validate/security_context_linux.go
  pkg/validate/selinux_linux.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/L, approved

#869 Add support for cri-dockerd
  cmd/crictl/main_unix.go
  cmd/crictl/main_windows.go
  docs/crictl.md
Labels: kind/feature, cncf-cla: yes, lgtm, size/S, approved

#858 fix ci for dockershim-critest
  hack/run-dockershim-critest.sh
Labels: cncf-cla: yes, size/XS, kind/design

#875 update containerd to 1.5.9
  .github/workflows/containerd.yml
Labels: kind/feature, cncf-cla: yes, lgtm, size/XS, kind/flake, kind/api-change, kind/failing-test, approved, kind/deprecation, kind/regression

#873 Use same grpc max message size as Kubelet
  cmd/crictl/main.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#852 images: use k8s-staging-test-infra/gcb-docker-gcloud
  images/cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#876 Bump docs to v1.23.0
  README.md
  docs/crictl.md
Labels: cncf-cla: yes, lgtm, size/XS, kind/documentation, approved
