Repository kubernetes-sigs/cri-tools, pull requests merged in 2022-10, with the labels that each got.

#997 Implement password input on the command line
  cmd/crictl/container.go
  cmd/crictl/image.go
  go.mod
  go.sum
  vendor/golang.org/x/term/AUTHORS
  vendor/golang.org/x/term/CONTRIBUTORS
  vendor/golang.org/x/term/term.go
  vendor/golang.org/x/term/terminal.go
  vendor/modules.txt
Labels: kind/feature, cncf-cla: yes, lgtm, size/M, approved

#995 Add recurring working areas to CONTRIBUTING
  CONTRIBUTING.md
Labels: cncf-cla: yes, lgtm, size/S, kind/documentation, approved

#1006 test-image: add test image for testing SupplementalGroups with predefined groups in the container image
  images/build
  images/image-predefined-group/Dockerfile
Labels: cncf-cla: yes, lgtm, size/S, approved

#1005 critest: added a validation case for SupplementalGroups with the pre-defined groups in the container image
  images/image-test/Dockerfile
  pkg/validate/consts.go
  pkg/validate/security_context_linux.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/M, approved
