Repository kubernetes-sigs/cri-tools, pull requests merged in 2022-02, with the labels that each got.

#884 Add backwards compatiblity to `Version` and `ListContainerStats` RPCs
  cmd/crictl/stats.go
  cmd/crictl/version.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/S, approved

#888 Update crictl ps to show pod name and repo image
  cmd/crictl/container.go
  cmd/crictl/display.go
  cmd/crictl/util.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#892 add annotation for pull
  cmd/crictl/container.go
  cmd/crictl/image.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/S, approved

#895 Type cast error messages to `string`
  pkg/validate/container.go
  pkg/validate/networking.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/XS, approved

#861 fix log info for mount test case
  pkg/validate/container_linux.go
Labels: cncf-cla: yes, lgtm, size/XS, kind/documentation, approved, ok-to-test

#863 fix security test case for hostpid
  pkg/validate/security_context_linux.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/XS, approved
