Repository kubernetes-sigs/cri-tools, pull requests merged in 2022-03, with the labels that each got.

#851 fix test case chmod syscall for arm64
  pkg/validate/security_context_linux.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/XS, approved

#886 Add `crictl statsp` command
  cmd/crictl/container_stats.go
  cmd/crictl/display.go
  cmd/crictl/main.go
  cmd/crictl/pod_stats.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/L, approved

#904 Add CRICTL_AUTH/CRICTL_CREDS env var option to crictl pull
  cmd/crictl/image.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/S, approved

#905 Fix CRI-O tests
  .github/workflows/crio.yml
Labels: cncf-cla: yes, size/XS, kind/failing-test, approved
