Repository kubernetes-sigs/cri-tools, pull requests merged in 2022-09, with the labels that each got.

#979 Print deleted digest when repo tags empty
  cmd/crictl/image.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/XS, approved

#968 Update version references in docs and go.mod
  README.md
  go.mod
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, size/S, kind/documentation, approved

#990 Cleanup owners
  OWNERS
  OWNERS_ALIASES
Labels: cncf-cla: yes, lgtm, size/S, kind/cleanup, approved
