Repository kubernetes-sigs/cri-tools, pull requests merged in 2023-08, with the labels that each got.

#1229 crictl: deduplicate display boilerplate
  cmd/crictl/container_stats.go
  cmd/crictl/pod_stats.go
  cmd/crictl/util.go
Labels: cncf-cla: yes, lgtm, size/L, kind/design, approved

#1236 Fix seccomp value in test
  pkg/validate/security_context_linux.go
Labels: cncf-cla: yes, lgtm, size/S, approved, kind/regression

#1239 Use previous and latest tag from git in release script
  hack/release-notes.sh
Labels: cncf-cla: yes, lgtm, size/XS, kind/failing-test, approved

#1240 Bump latest version in README.md
  README.md
Labels: cncf-cla: yes, lgtm, size/XS, kind/documentation, approved

#1242 Vendor Kubernetes v1.28.0
  go.mod
  go.sum
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, size/L, kind/cleanup, approved

#1243 Remove the Kubernetes incubator reference from README.md
  README.md
Labels: cncf-cla: yes, lgtm, size/XS, kind/documentation, approved

#1241 Add crictl events command
  cmd/crictl/events.go
  cmd/crictl/main.go
  cmd/crictl/templates.go
  cmd/crictl/util.go
  docs/crictl.md
  test/e2e/events_test.go
  test/framework/framework.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/L, approved

#1247 Add show pinned information for images
  cmd/crictl/display.go
  cmd/crictl/image.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/S, approved
