Repository kubernetes-sigs/cri-tools, pull requests merged in 2023-12, with the labels that each got.

#1294 ci: Switch to ubuntu 22.04 and go 1.21
  .github/workflows/build.yml
  .github/workflows/containerd.yml
  .github/workflows/crio.yml
  .github/workflows/e2e.yml
  .github/workflows/release.yml
Labels: cncf-cla: yes, lgtm, size/S, kind/cleanup, approved

#1295 adding imagefsinfo endpoint for both container and image filesystems
  cmd/crictl/image.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/M, approved

#1302 add support container runtime use systemd cgroups
  pkg/benchmark/pod.go
  pkg/benchmark/pod_container.go
  pkg/common/pod_config.go
  pkg/framework/util.go
  pkg/validate/multi_container_linux.go
  pkg/validate/networking.go
  pkg/validate/pod.go
  pkg/validate/pod_linux.go
  pkg/validate/security_context_linux.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/L, approved

#1306 Add darwin/arm64 to release binaries
  hack/release.sh
Labels: kind/feature, cncf-cla: yes, lgtm, size/XS, approved

#1308 Drop support for `linux/arm` platform
  hack/release.sh
Labels: cncf-cla: yes, lgtm, size/XS, kind/cleanup, approved

#1310 Serialize the container_filesystem and image_filesystem in addition for file stats.
  cmd/crictl/image.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/M, approved

#1312 Vendor Kubernetes v1.29.0-rc.2
  go.mod
  go.sum
  vendor/k8s.io/api/batch/v1/generated.proto
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/api/batch/v1/types_swagger_doc_generated.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, size/L, kind/cleanup, approved

#1316 Update vendored Kubernetes to v1.29.0
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, size/L, kind/cleanup, approved

#1315 Add a .snyk file to configure the Snyk security scanner
  .snyk
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1320 Provide precompiled manpage version
  .github/workflows/build.yml
  docs/crictl.1
  hack/verify-docs.sh
Labels: cncf-cla: yes, lgtm, size/XL, kind/documentation, approved
