Repository kubernetes-sigs/cri-tools, pull requests merged in 2023-01, with the labels that each got.

#1057 Add support for displaying windows pod stats
  cmd/crictl/pod_stats.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/M, approved

#1053 Switch away from Docker Hub to avoid rate limits
  pkg/benchmark/image.go
  pkg/framework/util.go
  pkg/validate/consts.go
  pkg/validate/multi_container_linux.go
  pkg/validate/security_context_linux.go
Labels: cncf-cla: yes, lgtm, size/S, kind/flake, approved

#1058 Increase default timeout on Windows
  cmd/crictl/main.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/XS, sig/windows, approved

#1063 fix(docs): add tip on latest version
  docs/crictl.md
Labels: cncf-cla: yes, lgtm, size/XS, kind/documentation, approved

#1065 fix(docs): add a note about other supported platforms
  docs/crictl.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1062 Update ginkgo and gomega
  go.mod
  go.sum
  pkg/framework/test_context.go
  vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md
  vendor/github.com/onsi/ginkgo/v2/README.md
  vendor/github.com/onsi/ginkgo/v2/core_dsl.go
  vendor/github.com/onsi/ginkgo/v2/decorator_dsl.go
  vendor/github.com/onsi/ginkgo/v2/formatter/formatter.go
  vendor/github.com/onsi/ginkgo/v2/ginkgo/generators/bootstrap_command.go
  vendor/github.com/onsi/ginkgo/v2/ginkgo/generators/generate_command.go
  vendor/github.com/onsi/ginkgo/v2/ginkgo/generators/generators_common.go
  vendor/github.com/onsi/ginkgo/v2/ginkgo/internal/run.go
  vendor/github.com/onsi/ginkgo/v2/ginkgo/outline/ginkgo.go
  vendor/github.com/onsi/ginkgo/v2/ginkgo/outline/outline.go
  vendor/github.com/onsi/ginkgo/v2/internal/group.go
  vendor/github.com/onsi/ginkgo/v2/internal/node.go
  vendor/github.com/onsi/ginkgo/v2/internal/ordering.go
  vendor/github.com/onsi/ginkgo/v2/internal/parallel_support/client_server.go
  vendor/github.com/onsi/ginkgo/v2/internal/parallel_support/http_client.go
  vendor/github.com/onsi/ginkgo/v2/internal/parallel_support/http_server.go
  vendor/github.com/onsi/ginkgo/v2/internal/parallel_support/rpc_client.go
  vendor/github.com/onsi/ginkgo/v2/internal/parallel_support/server_handler.go
  vendor/github.com/onsi/ginkgo/v2/internal/progress_report.go
  vendor/github.com/onsi/ginkgo/v2/internal/report_entry.go
  vendor/github.com/onsi/ginkgo/v2/internal/suite.go
  vendor/github.com/onsi/ginkgo/v2/internal/writer.go
  vendor/github.com/onsi/ginkgo/v2/reporters/default_reporter.go
  vendor/github.com/onsi/ginkgo/v2/reporters/deprecated_reporter.go
  vendor/github.com/onsi/ginkgo/v2/reporters/junit_report.go
  vendor/github.com/onsi/ginkgo/v2/reporters/reporter.go
  vendor/github.com/onsi/ginkgo/v2/reporting_dsl.go
  vendor/github.com/onsi/ginkgo/v2/types/code_location.go
  vendor/github.com/onsi/ginkgo/v2/types/config.go
  vendor/github.com/onsi/ginkgo/v2/types/deprecation_support.go
  vendor/github.com/onsi/ginkgo/v2/types/errors.go
  vendor/github.com/onsi/ginkgo/v2/types/report_entry.go
  vendor/github.com/onsi/ginkgo/v2/types/types.go
  vendor/github.com/onsi/ginkgo/v2/types/version.go
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/gexec/session.go
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/internal/async_assertion.go
  vendor/github.com/onsi/gomega/internal/gomega.go
  vendor/github.com/onsi/gomega/types/types.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, size/XXL, kind/cleanup, approved

#1064 Pass `nil` as tracer provider
  cmd/crictl/main.go
  go.mod
  pkg/framework/util.go
Labels: cncf-cla: yes, lgtm, size/S, kind/cleanup, approved

#1066 Update docs version to match latest release
  README.md
  docs/crictl.md
Labels: cncf-cla: yes, lgtm, size/XS, kind/documentation, approved

#1074 Makefile: pass in a custom variable GOARCH
  Makefile
Labels: kind/feature, cncf-cla: yes, lgtm, size/S, approved
