Repository kubernetes-sigs/cri-tools, pull requests merged in 2023-02, with the labels that each got.

#1085 Makefile support cross compilation, build_bin_path optimization
  Makefile
Labels: kind/feature, cncf-cla: yes, lgtm, size/S, approved

#1084 crictl stats add name row
  cmd/crictl/container_stats.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/XS, approved

#1090 crictl config add list flag
  cmd/crictl/config.go
  cmd/crictl/display.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/S, approved

#1092 fix crictl config list display error
  cmd/crictl/config.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/S, approved

#1099 Run GitHub actions by `push` only on `master` and tags
  .github/workflows/build.yml
  .github/workflows/containerd.yml
  .github/workflows/crio.yml
  .github/workflows/e2e.yml
Labels: cncf-cla: yes, lgtm, size/M, kind/cleanup, approved

#1088 crictl code and args optimization
  cmd/crictl/attach.go
  cmd/crictl/config.go
  cmd/crictl/container.go
  cmd/crictl/container_stats.go
  cmd/crictl/exec.go
  cmd/crictl/image.go
  cmd/crictl/info.go
  cmd/crictl/logs.go
  cmd/crictl/pod_stats.go
  cmd/crictl/portforward.go
  cmd/crictl/sandbox.go
  cmd/crictl/version.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/XL, approved
