Repository kubernetes-sigs/cri-tools, pull requests merged in 2023-06, with the labels that each got.

#1183 Pin `FROM` images to tags
  images/hostnet-nginx/Dockerfile
  images/image-predefined-group/Dockerfile
  images/image-test/Dockerfile
  images/image-user/Dockerfile
Labels: cncf-cla: yes, lgtm, size/XS, kind/cleanup, approved

#1187 update actions using node12 to latest version using node16
  .github/dependabot.yml
  .github/workflows/build.yml
  .github/workflows/containerd.yml
  .github/workflows/crio.yml
  .github/workflows/e2e.yml
  .github/workflows/release.yml
Labels: cncf-cla: yes, lgtm, size/M, kind/cleanup, approved

#1186 Add image build test to GitHub actions
  .github/workflows/build.yml
  images/build
Labels: cncf-cla: yes, lgtm, size/L, kind/failing-test, approved

#1199 Typo fix in critest
  pkg/framework/test_context.go
  pkg/validate/pod.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/S, approved, ok-to-test
