Repository kubernetes-sigs/cri-tools, pull requests merged in 2023-07, with the labels that each got.

#1202 fix listCoontainerStats not filter
  pkg/validate/container.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/S, approved

#1210 Revert "fix listCoontainerStats not filter"
  pkg/validate/container.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/S, approved

#1208 Bump Kubernetes to v1.27.3
  go.mod
  go.sum
  vendor/k8s.io/api/batch/v1/generated.proto
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/api/batch/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/apimachinery/pkg/types/namespacedname.go
  vendor/k8s.io/client-go/discovery/discovery_client.go
  vendor/k8s.io/client-go/openapi/client.go
  vendor/k8s.io/client-go/openapi/groupversion.go
  vendor/k8s.io/kubernetes/pkg/apis/core/types.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, size/L, kind/cleanup, approved

#1216 Drop support for docker log format
  go.mod
  go.sum
  pkg/validate/container.go
  vendor/github.com/docker/docker/daemon/logger/jsonfilelog/jsonlog/jsonlog.go
  vendor/github.com/docker/docker/daemon/logger/jsonfilelog/jsonlog/jsonlogbytes.go
  vendor/github.com/docker/docker/daemon/logger/jsonfilelog/jsonlog/time_marshalling.go
  vendor/github.com/pkg/errors/.gitignore
  vendor/github.com/pkg/errors/.travis.yml
  vendor/github.com/pkg/errors/LICENSE
  vendor/github.com/pkg/errors/Makefile
  vendor/github.com/pkg/errors/README.md
  vendor/github.com/pkg/errors/appveyor.yml
  vendor/github.com/pkg/errors/errors.go
  vendor/github.com/pkg/errors/go113.go
  vendor/github.com/pkg/errors/stack.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, size/XL, kind/cleanup, approved

#1215 Use google/uuid
  go.mod
  go.sum
  pkg/framework/util.go
  vendor/github.com/pborman/uuid/.travis.yml
  vendor/github.com/pborman/uuid/CONTRIBUTING.md
  vendor/github.com/pborman/uuid/CONTRIBUTORS
  vendor/github.com/pborman/uuid/LICENSE
  vendor/github.com/pborman/uuid/README.md
  vendor/github.com/pborman/uuid/dce.go
  vendor/github.com/pborman/uuid/doc.go
  vendor/github.com/pborman/uuid/hash.go
  vendor/github.com/pborman/uuid/marshal.go
  vendor/github.com/pborman/uuid/node.go
  vendor/github.com/pborman/uuid/sql.go
  vendor/github.com/pborman/uuid/time.go
  vendor/github.com/pborman/uuid/util.go
  vendor/github.com/pborman/uuid/uuid.go
  vendor/github.com/pborman/uuid/version1.go
  vendor/github.com/pborman/uuid/version4.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, size/XL, kind/cleanup, approved

#1214 Fix release notes job
  .github/workflows/release.yml
  hack/release-notes.sh
Labels: cncf-cla: yes, lgtm, size/S, kind/failing-test, approved

#1218 Update version in README
  README.md
Labels: cncf-cla: yes, lgtm, size/XS, kind/documentation, approved

#1224 Use `UserSpecifiedImage` for seccomp tests
  pkg/validate/security_context_linux.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/XS, approved

#1226 Make `haircommander` an approver
  OWNERS
Labels: cncf-cla: yes, lgtm, size/XS, kind/documentation, approved
