Repository kubernetes-sigs/cri-tools, pull requests merged in 2023-04, with the labels that each got.

#1132 Improve text formatting
  docs/crictl.md
Labels: cncf-cla: yes, lgtm, size/M, kind/documentation, approved

#1133 bump to kube 1.27 and go 1.20
  .github/workflows/build.yml
  .github/workflows/containerd.yml
  .github/workflows/crio.yml
  .github/workflows/e2e.yml
  .github/workflows/release.yml
  .golangci.yml
  Makefile
  go.mod
  pkg/validate/container.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, size/M, kind/cleanup, approved

#1135 Update CI badges
  README.md
Labels: cncf-cla: yes, lgtm, size/XS, kind/documentation, approved

#1138 Disable dependency gathering for release notes
  hack/release-notes.sh
Labels: cncf-cla: yes, lgtm, size/XS, kind/failing-test, approved

#1142 Download release notes tool binary directly
  hack/release-notes.sh
Labels: cncf-cla: yes, lgtm, size/XS, kind/cleanup, approved

#1140 Various Makefile improvements
  Makefile
Labels: kind/bug, cncf-cla: yes, lgtm, size/S, approved
