Repository kubernetes-sigs/cri-tools, pull requests merged in 2024-06, with the labels that each got.

#1429 Fixes invalid JSON in crictl info
  cmd/crictl/util.go
  cmd/crictl/util_test.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/L, approved

#1440 Revert "Fixes invalid JSON in crictl info"
  cmd/crictl/util.go
  cmd/crictl/util_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#1445 Update e2e test suite
  .github/workflows/crio.yml
  .github/workflows/e2e.yml
  .gitignore
  Makefile
  test/e2e/events_test.go
  test/e2e/help_test.go
  test/e2e/info_test.go
  test/e2e/pull_test.go
  test/e2e/suite_test.go
  test/e2e/version_test.go
  test/framework/framework.go
Labels: cncf-cla: yes, lgtm, size/L, kind/cleanup, approved

#1446 Fixes invalid JSON in crictl info
  cmd/crictl/util.go
  cmd/crictl/util_test.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/L, approved

#1450 Revert "Fixes invalid JSON in crictl info"
  cmd/crictl/util.go
  cmd/crictl/util_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#1448 Add `--pull-timeout` flag to `crictl` `create`, `run` and `pull` commands
  cmd/crictl/container.go
  cmd/crictl/image.go
  go.mod
  pkg/framework/util.go
  pkg/validate/image.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/L, approved

#1458 `crictl run`: Rename `--timeout`/`-t` to `--cancel-timeout`/`-T`
  cmd/crictl/container.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/XS, approved

#1457 Fix `pull-timeout` flag for `crictl pull`
  cmd/crictl/image.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/XS, approved

#1462 Make image RPCs interruptable using Ctrl-C
  cmd/crictl/image.go
  cmd/crictl/util.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/M, approved

#1468 Make all RPC's interruptable
  cmd/crictl/attach.go
  cmd/crictl/container.go
  cmd/crictl/container_stats.go
  cmd/crictl/exec.go
  cmd/crictl/image.go
  cmd/crictl/info.go
  cmd/crictl/logs.go
  cmd/crictl/pod_metrics.go
  cmd/crictl/pod_stats.go
  cmd/crictl/portforward.go
  cmd/crictl/runtime_config.go
  cmd/crictl/sandbox.go
  cmd/crictl/version.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/L, approved

#1469 Add support to reopen container logs
  cmd/crictl/logs.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/S, approved

#1449 Add `crictl [create,runp,run,pull] jsonschema` subcommands
  cmd/crictl/container.go
  cmd/crictl/image.go
  cmd/crictl/sandbox.go
  cmd/crictl/util.go
  docs/crictl.1
  docs/crictl.md
  go.mod
  go.sum
  test/e2e/pull_test.go
  vendor/github.com/bahlo/generic-list-go/LICENSE
  vendor/github.com/bahlo/generic-list-go/README.md
  vendor/github.com/bahlo/generic-list-go/list.go
  vendor/github.com/buger/jsonparser/.gitignore
  vendor/github.com/buger/jsonparser/.travis.yml
  vendor/github.com/buger/jsonparser/Dockerfile
  vendor/github.com/buger/jsonparser/LICENSE
  vendor/github.com/buger/jsonparser/Makefile
  vendor/github.com/buger/jsonparser/README.md
  vendor/github.com/buger/jsonparser/bytes.go
  vendor/github.com/buger/jsonparser/bytes_safe.go
  vendor/github.com/buger/jsonparser/bytes_unsafe.go
  vendor/github.com/buger/jsonparser/escape.go
  vendor/github.com/buger/jsonparser/fuzz.go
  vendor/github.com/buger/jsonparser/oss-fuzz-build.sh
  vendor/github.com/buger/jsonparser/parser.go
  vendor/github.com/invopop/jsonschema/.gitignore
  vendor/github.com/invopop/jsonschema/.golangci.yml
  vendor/github.com/invopop/jsonschema/COPYING
  vendor/github.com/invopop/jsonschema/README.md
  vendor/github.com/invopop/jsonschema/comment_extractor.go
  vendor/github.com/invopop/jsonschema/id.go
  vendor/github.com/invopop/jsonschema/reflect.go
  vendor/github.com/invopop/jsonschema/schema.go
  vendor/github.com/invopop/jsonschema/utils.go
  vendor/github.com/mailru/easyjson/LICENSE
  vendor/github.com/mailru/easyjson/buffer/pool.go
  vendor/github.com/mailru/easyjson/jwriter/writer.go
  vendor/github.com/wk8/go-ordered-map/v2/.gitignore
  vendor/github.com/wk8/go-ordered-map/v2/.golangci.yml
  vendor/github.com/wk8/go-ordered-map/v2/CHANGELOG.md
  vendor/github.com/wk8/go-ordered-map/v2/LICENSE
  vendor/github.com/wk8/go-ordered-map/v2/Makefile
  vendor/github.com/wk8/go-ordered-map/v2/README.md
  vendor/github.com/wk8/go-ordered-map/v2/json.go
  vendor/github.com/wk8/go-ordered-map/v2/orderedmap.go
  vendor/github.com/wk8/go-ordered-map/v2/yaml.go
  vendor/modules.txt
Labels: kind/feature, cncf-cla: yes, lgtm, size/XXL, approved
