Repository kubernetes-sigs/cri-tools, pull requests merged in 2024-05, with the labels that each got.

#1415 Enable and fix `perfsprint` linter
  .golangci.yml
  cmd/crictl/attach.go
  cmd/crictl/completion.go
  cmd/crictl/container.go
  cmd/crictl/container_stats.go
  cmd/crictl/exec.go
  cmd/crictl/image.go
  cmd/crictl/logs.go
  cmd/crictl/main.go
  cmd/crictl/portforward.go
  cmd/crictl/sandbox.go
  pkg/benchmark/util.go
  pkg/validate/container.go
  pkg/validate/multi_container_linux.go
  pkg/validate/security_context_linux.go
Labels: cncf-cla: yes, lgtm, size/L, kind/cleanup, approved

#1423 Move project under `sigs.k8s.io` namespace
  Makefile
  cmd/crictl/config.go
  cmd/crictl/main.go
  cmd/critest/cri_test.go
  docs/developer-guide.md
  go.mod
  hack/release.sh
  pkg/benchmark/container.go
  pkg/benchmark/image.go
  pkg/benchmark/pod.go
  pkg/benchmark/pod_container.go
  pkg/framework/util.go
  pkg/validate/apparmor_linux.go
  pkg/validate/consts.go
  pkg/validate/container.go
  pkg/validate/container_linux.go
  pkg/validate/image.go
  pkg/validate/multi_container_linux.go
  pkg/validate/networking.go
  pkg/validate/pod.go
  pkg/validate/pod_linux.go
  pkg/validate/runtime_info.go
  pkg/validate/security_context_linux.go
  pkg/validate/selinux_linux.go
  pkg/validate/streaming.go
  pkg/validate/streaming_linux.go
  test/e2e/suite_test.go
Labels: cncf-cla: yes, lgtm, size/M, kind/api-change, approved

#1418 Fix latest version in README.md
  README.md
Labels: cncf-cla: yes, lgtm, size/XS, kind/documentation, approved

#1387 Bump golang to v1.22 in CI
  .github/workflows/build.yml
  .github/workflows/containerd.yml
  .github/workflows/crio.yml
  .github/workflows/e2e.yml
  .github/workflows/release.yml
Labels: cncf-cla: yes, lgtm, size/M, kind/cleanup, approved

#1435 Gomod tools
  docs/crictl.1
  hack/install-cri-dockerd.sh
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  hack/verify-docs.sh
Labels: cncf-cla: yes, lgtm, size/XXL, kind/cleanup, approved
