Repository kubernetes-sigs/cri-tools, pull requests merged in 2024-03, with the labels that each got.

#1344 KEP-3857: Recursive Read-only (RRO) mounts
  cmd/crictl/container.go
  cmd/crictl/image.go
  cmd/crictl/info.go
  cmd/crictl/sandbox.go
  cmd/crictl/util.go
  pkg/validate/container_linux.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/L, approved

#1383 Support websocket transport for exec and attach
  cmd/crictl/attach.go
  cmd/crictl/exec.go
  cmd/crictl/util.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/M, approved

#1369 Do not auto find runtime handler for user namespaces tests
  pkg/framework/util.go
  pkg/validate/security_context_linux.go
Labels: cncf-cla: yes, lgtm, size/M, kind/cleanup, approved
