Repository kubernetes-sigs/cri-tools, pull requests merged in 2024-07, with the labels that each got.

#1475 ci: switch to macOS 12
  .github/workflows/build.yml
Labels: cncf-cla: yes, lgtm, size/XS, kind/cleanup, approved

#1472 Fix invalid context on `Status` RPC
  cmd/crictl/info.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/XS, approved

#1474 Sort commands by their name
  cmd/crictl/main.go
Labels: cncf-cla: yes, lgtm, size/XS, kind/documentation, approved

#1489 userns: Skip tests if the host doesn't support idmap mounts
  pkg/validate/security_context_linux.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/L, kind/failing-test, approved

#1470 Update golangci-lint to v1.59.1 and fix lints
  .github/workflows/build.yml
  .golangci.yml
  Makefile
  cmd/crictl/container.go
  cmd/crictl/image.go
  cmd/crictl/main.go
  cmd/crictl/sandbox.go
  cmd/crictl/util.go
  pkg/common/file.go
  pkg/framework/util.go
  pkg/validate/runtime_info.go
  pkg/validate/security_context_linux.go
Labels: cncf-cla: yes, lgtm, size/L, kind/cleanup, approved

#1492 [release-1.30] userns: Skip tests if the host doesn't support idmap mounts
  .github/workflows/build.yml
  pkg/validate/security_context_linux.go
Labels: cncf-cla: yes, lgtm, size/L, kind/failing-test, approved

#1473 Add crictl `update-runtime-config` command
  cmd/crictl/main.go
  cmd/crictl/update_runtime_config.go
  docs/crictl.1
  docs/crictl.md
Labels: kind/feature, cncf-cla: yes, lgtm, size/L, approved

#1486 Fixes invalid JSON in crictl info
  cmd/crictl/util.go
  cmd/crictl/util_test.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/L, approved

#1495 Fix parent dir retrieval lint
  pkg/validate/security_context_linux.go
Labels: cncf-cla: yes, lgtm, size/XS, kind/cleanup, approved

#1439 Add stats label filter test
  pkg/framework/util.go
  pkg/validate/container.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/S, approved

#1493 Fix invalid JSON for multiple images/containers/pods
  cmd/crictl/container.go
  cmd/crictl/image.go
  cmd/crictl/info.go
  cmd/crictl/sandbox.go
  cmd/crictl/util.go
  cmd/crictl/util_test.go
  test/e2e/inspecti_test.go
  test/e2e/inspectp_test.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/XL, approved

#1497 Remove use of deprecated proto packages
  cmd/crictl/util.go
  go.mod
  vendor/github.com/golang/protobuf/AUTHORS
  vendor/github.com/golang/protobuf/CONTRIBUTORS
  vendor/github.com/golang/protobuf/LICENSE
  vendor/github.com/golang/protobuf/jsonpb/decode.go
  vendor/github.com/golang/protobuf/jsonpb/encode.go
  vendor/github.com/golang/protobuf/jsonpb/json.go
  vendor/github.com/golang/protobuf/proto/buffer.go
  vendor/github.com/golang/protobuf/proto/defaults.go
  vendor/github.com/golang/protobuf/proto/deprecated.go
  vendor/github.com/golang/protobuf/proto/discard.go
  vendor/github.com/golang/protobuf/proto/extensions.go
  vendor/github.com/golang/protobuf/proto/properties.go
  vendor/github.com/golang/protobuf/proto/proto.go
  vendor/github.com/golang/protobuf/proto/registry.go
  vendor/github.com/golang/protobuf/proto/text_decode.go
  vendor/github.com/golang/protobuf/proto/text_encode.go
  vendor/github.com/golang/protobuf/proto/wire.go
  vendor/github.com/golang/protobuf/proto/wrappers.go
  vendor/google.golang.org/protobuf/internal/editionssupport/editions.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_init.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_resolve.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_validate.go
  vendor/google.golang.org/protobuf/reflect/protodesc/editions.go
  vendor/google.golang.org/protobuf/reflect/protodesc/proto.go
  vendor/google.golang.org/protobuf/types/descriptorpb/descriptor.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.pb.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, size/XXL, kind/cleanup, approved

#1491 Make `crictl events` interruptable
  cmd/crictl/events.go
Labels: cncf-cla: yes, lgtm, size/XS, kind/cleanup, approved

#1464 Add OCI Volume Source support to `crictl [create|run] --with-pull`
  cmd/crictl/container.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/S, approved

#1496 Enable more linters and update config
  .golangci.yml
  cmd/crictl/attach.go
  cmd/crictl/completion.go
  cmd/crictl/config.go
  cmd/crictl/container.go
  cmd/crictl/container_stats.go
  cmd/crictl/container_test.go
  cmd/crictl/display.go
  cmd/crictl/events.go
  cmd/crictl/exec.go
  cmd/crictl/image.go
  cmd/crictl/image_test.go
  cmd/crictl/main.go
  cmd/crictl/pod_metrics.go
  cmd/crictl/pod_stats.go
  cmd/crictl/portforward.go
  cmd/crictl/runtime_config.go
  cmd/crictl/sandbox.go
  cmd/crictl/templates.go
  cmd/crictl/util.go
  cmd/crictl/util_test.go
  cmd/critest/cri_test.go
  pkg/benchmark/container.go
  pkg/benchmark/image.go
  pkg/benchmark/pod.go
  pkg/benchmark/pod_container.go
  pkg/benchmark/util.go
  pkg/common/config.go
  pkg/common/file.go
  pkg/framework/framework.go
  pkg/framework/test_context.go
  pkg/framework/util.go
  pkg/validate/apparmor_linux.go
  pkg/validate/consts.go
  pkg/validate/container.go
  pkg/validate/container_linux.go
  pkg/validate/image.go
  pkg/validate/multi_container_linux.go
  pkg/validate/networking.go
  pkg/validate/pod.go
  pkg/validate/pod_linux.go
  pkg/validate/runtime_info.go
  pkg/validate/security_context_linux.go
  pkg/validate/selinux_linux.go
  pkg/validate/streaming.go
  pkg/validate/streaming_linux.go
  test/e2e/events_test.go
  test/e2e/help_test.go
  test/e2e/info_test.go
  test/e2e/inspecti_test.go
  test/e2e/inspectp_test.go
  test/e2e/pull_test.go
  test/e2e/suite_test.go
  test/e2e/version_test.go
  test/framework/framework.go
Labels: cncf-cla: yes, lgtm, size/XL, kind/cleanup, approved

#1507 Revert "Enable and fix all gocritic linters"
  .golangci.yml
  cmd/crictl/attach.go
  cmd/crictl/completion.go
  cmd/crictl/config.go
  cmd/crictl/container.go
  cmd/crictl/container_stats.go
  cmd/crictl/container_test.go
  cmd/crictl/display.go
  cmd/crictl/events.go
  cmd/crictl/exec.go
  cmd/crictl/image.go
  cmd/crictl/image_test.go
  cmd/crictl/main.go
  cmd/crictl/pod_metrics.go
  cmd/crictl/pod_stats.go
  cmd/crictl/portforward.go
  cmd/crictl/runtime_config.go
  cmd/crictl/sandbox.go
  cmd/crictl/templates.go
  cmd/crictl/util.go
  cmd/crictl/util_test.go
  cmd/critest/cri_test.go
  pkg/benchmark/container.go
  pkg/benchmark/image.go
  pkg/benchmark/pod.go
  pkg/benchmark/pod_container.go
  pkg/benchmark/util.go
  pkg/common/config.go
  pkg/common/file.go
  pkg/framework/framework.go
  pkg/framework/test_context.go
  pkg/framework/util.go
  pkg/validate/apparmor_linux.go
  pkg/validate/consts.go
  pkg/validate/container.go
  pkg/validate/container_linux.go
  pkg/validate/image.go
  pkg/validate/multi_container_linux.go
  pkg/validate/networking.go
  pkg/validate/pod.go
  pkg/validate/pod_linux.go
  pkg/validate/runtime_info.go
  pkg/validate/security_context_linux.go
  pkg/validate/selinux_linux.go
  pkg/validate/streaming.go
  pkg/validate/streaming_linux.go
  test/e2e/events_test.go
  test/e2e/help_test.go
  test/e2e/info_test.go
  test/e2e/inspecti_test.go
  test/e2e/inspectp_test.go
  test/e2e/pull_test.go
  test/e2e/suite_test.go
  test/e2e/version_test.go
  test/framework/framework.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#1508 Fix lint timeout
  .golangci.yml
Labels: cncf-cla: yes, lgtm, size/XS, kind/failing-test, approved

#1509 Remove log message for AppArmor profiles
  pkg/validate/apparmor_linux.go
Labels: cncf-cla: yes, lgtm, size/XS, kind/cleanup, approved

#1510 Fix `godot` linter
  .golangci.yml
  cmd/crictl/attach.go
  cmd/crictl/container.go
  cmd/crictl/exec.go
  cmd/crictl/image.go
  cmd/crictl/main.go
  cmd/crictl/portforward.go
  cmd/crictl/runtime_config.go
  cmd/crictl/util.go
  cmd/critest/cri_test.go
  pkg/benchmark/image.go
  pkg/benchmark/util.go
  pkg/common/config.go
  pkg/common/file.go
  pkg/framework/framework.go
  pkg/framework/util.go
  pkg/validate/consts.go
  pkg/validate/container.go
  pkg/validate/image.go
  pkg/validate/networking.go
  pkg/validate/streaming.go
  test/e2e/events_test.go
  test/e2e/help_test.go
  test/e2e/info_test.go
  test/e2e/inspecti_test.go
  test/e2e/inspectp_test.go
  test/e2e/pull_test.go
  test/e2e/suite_test.go
  test/e2e/version_test.go
  test/framework/framework.go
Labels: cncf-cla: yes, lgtm, size/L, kind/cleanup, approved

#1511 Enable linters which do not report anything
  .golangci.yml
Labels: cncf-cla: yes, lgtm, size/S, kind/cleanup, approved

#1513 Fix and enable `gci` linter
  .golangci.yml
  cmd/crictl/container.go
  cmd/crictl/container_test.go
  cmd/crictl/image_test.go
  cmd/crictl/main.go
  cmd/crictl/sandbox.go
  pkg/benchmark/container.go
  pkg/benchmark/image.go
  pkg/benchmark/pod.go
  pkg/benchmark/pod_container.go
  pkg/framework/framework.go
  pkg/framework/util.go
  pkg/validate/apparmor_linux.go
  pkg/validate/consts.go
  pkg/validate/container.go
  pkg/validate/container_linux.go
  pkg/validate/image.go
  pkg/validate/multi_container_linux.go
  pkg/validate/networking.go
  pkg/validate/pod.go
  pkg/validate/pod_linux.go
  pkg/validate/runtime_info.go
  pkg/validate/security_context_linux.go
  pkg/validate/selinux_linux.go
  pkg/validate/streaming.go
  pkg/validate/streaming_linux.go
  test/e2e/suite_test.go
Labels: cncf-cla: yes, lgtm, size/L, kind/cleanup, approved

#1515 Fix `whitespace` linter
  .golangci.yml
  cmd/crictl/container_stats.go
  cmd/crictl/exec.go
  cmd/crictl/pod_stats.go
  cmd/crictl/sandbox.go
  pkg/framework/util.go
Labels: cncf-cla: yes, lgtm, size/XS, kind/cleanup, approved

#1516 Fix `nolintlint` linter
  .golangci.yml
  cmd/crictl/container.go
  cmd/crictl/sandbox.go
Labels: cncf-cla: yes, lgtm, size/XS, kind/cleanup, approved

#1518 Fix `emptyStringTest` linter
  .golangci.yml
  cmd/crictl/events.go
Labels: cncf-cla: yes, lgtm, size/XS, kind/cleanup, approved

#1519 Fix `importshadow` linter
  .golangci.yml
  cmd/crictl/exec.go
  cmd/crictl/portforward.go
  pkg/validate/image.go
  pkg/validate/streaming.go
Labels: cncf-cla: yes, lgtm, size/M, kind/cleanup, approved

#1438 KEP-3619: Fine-grained SupplementalGroups control
  go.mod
  go.sum
  pkg/validate/security_context_linux.go
  vendor/k8s.io/cri-api/pkg/apis/runtime/v1/api.pb.go
  vendor/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto
  vendor/modules.txt
Labels: kind/feature, cncf-cla: yes, lgtm, size/XXL, approved

#1523 Fix `unnamedResult` linter
  .golangci.yml
  cmd/crictl/image.go
  pkg/validate/container.go
  pkg/validate/container_linux.go
  pkg/validate/multi_container_linux.go
  pkg/validate/pod.go
  pkg/validate/security_context_linux.go
Labels: cncf-cla: yes, lgtm, size/M, kind/cleanup, approved

#1524 Fix `bodyclose` linter
  .golangci.yml
  pkg/validate/networking.go
Labels: cncf-cla: yes, lgtm, size/S, kind/cleanup, approved

#1527 Print portforward stdio only on error
  pkg/validate/streaming.go
Labels: cncf-cla: yes, lgtm, size/S, kind/cleanup, approved

#1526 Fix `errchkjson` and `errorlint` linters
  .golangci.yml
  cmd/crictl/container.go
  cmd/crictl/events.go
  cmd/crictl/templates.go
  pkg/benchmark/util.go
  pkg/framework/test_context.go
  pkg/framework/util.go
Labels: cncf-cla: yes, lgtm, size/M, kind/cleanup, approved

#1525 Fix `hugeParam` linter
  .golangci.yml
  cmd/crictl/container.go
  cmd/crictl/container_stats.go
  cmd/crictl/container_test.go
  cmd/crictl/sandbox.go
  pkg/common/file.go
  pkg/framework/test_context.go
Labels: cncf-cla: yes, lgtm, size/L, kind/cleanup, approved

#1529 Enable more linters and update config
  .golangci.yml
  cmd/crictl/completion.go
  cmd/crictl/config.go
  cmd/crictl/container.go
  cmd/crictl/container_stats.go
  cmd/crictl/container_test.go
  cmd/crictl/crictl_suite_test.go
  cmd/crictl/display.go
  cmd/crictl/exec.go
  cmd/crictl/image.go
  cmd/crictl/logs.go
  cmd/crictl/pod_stats.go
  cmd/crictl/sandbox.go
  cmd/crictl/templates_test.go
  cmd/crictl/util_test.go
  cmd/critest/cri_test.go
  pkg/benchmark/benchmark.go
  pkg/benchmark/image.go
  pkg/validate/container.go
  pkg/validate/e2e.go
  pkg/validate/image.go
  pkg/validate/runtime_info.go
  pkg/validate/security_context_linux.go
  test/e2e/suite_test.go
Labels: cncf-cla: yes, lgtm, size/L, kind/cleanup, approved

#1532 Fix `ginkgolinter` linter
  .golangci.yml
  cmd/crictl/util_test.go
  pkg/validate/apparmor_linux.go
  pkg/validate/container.go
  pkg/validate/container_linux.go
  pkg/validate/image.go
  pkg/validate/runtime_info.go
  pkg/validate/security_context_linux.go
  test/framework/framework.go
Labels: cncf-cla: yes, lgtm, size/M, kind/cleanup, approved

#1535 Enable and fix `errcheck` linter
  .golangci.yml
  cmd/crictl/util.go
  cmd/crictl/version.go
  cmd/critest/cri_test.go
  pkg/benchmark/container.go
  pkg/benchmark/image.go
  pkg/benchmark/pod_container.go
  pkg/validate/apparmor_linux.go
  pkg/validate/container.go
  pkg/validate/container_linux.go
  pkg/validate/networking.go
  pkg/validate/pod.go
  pkg/validate/pod_linux.go
  pkg/validate/security_context_linux.go
  pkg/validate/selinux_linux.go
  pkg/validate/streaming.go
  pkg/validate/streaming_linux.go
Labels: cncf-cla: yes, lgtm, size/L, kind/cleanup, approved

#1537 Enable and fix `goconst` linter
  .golangci.yml
  cmd/crictl/container.go
  cmd/crictl/container_stats.go
  cmd/crictl/events.go
  cmd/crictl/image.go
  cmd/crictl/info.go
  cmd/crictl/main.go
  cmd/crictl/pod_metrics.go
  cmd/crictl/pod_stats.go
  cmd/crictl/sandbox.go
  cmd/crictl/templates.go
  cmd/crictl/util.go
  cmd/crictl/util_test.go
  pkg/common/file.go
  pkg/framework/test_context.go
  pkg/framework/util.go
  pkg/validate/consts.go
  pkg/validate/image.go
  pkg/validate/security_context_linux.go
Labels: cncf-cla: yes, lgtm, size/L, kind/cleanup, approved
