Repository kubernetes-sigs/cri-tools, pull requests merged in 2024-10, with the labels that each got.

#1618 Pin Kubernetes to v1.31.1
  go.mod
  go.sum
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, size/M, kind/cleanup, approved

#1603 crictl exec: allow running single command in multiple containers
  cmd/crictl/exec.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/L, approved

#1625 Pin `k8s.io/{api,apimachinery,client-go}` to v0.31.1
  go.mod
  go.sum
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/apimachinery/pkg/api/meta/OWNERS
  vendor/k8s.io/apimachinery/pkg/api/resource/quantity.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/OWNERS
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/unstructured.go
  vendor/k8s.io/apimachinery/pkg/labels/selector.go
  vendor/k8s.io/apimachinery/pkg/runtime/interfaces.go
  vendor/k8s.io/apimachinery/pkg/runtime/serializer/cbor/internal/modes/encode.go
  vendor/k8s.io/apimachinery/pkg/util/validation/validation.go
  vendor/k8s.io/client-go/rest/request.go
  vendor/k8s.io/client-go/tools/remotecommand/v4.go
  vendor/k8s.io/client-go/transport/cache_go118.go
  vendor/k8s.io/client-go/transport/round_trippers.go
  vendor/k8s.io/client-go/util/workqueue/delaying_queue.go
  vendor/k8s.io/utils/strings/slices/slices.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, size/L, kind/cleanup, approved

#1622 crictl exec: add `--quiet/-q`, `--ignore-error/-e` and `--parallel` flags
  cmd/crictl/exec.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/M, approved

#1632 crictl ps, inspect: allow pod namespace filtering
  cmd/crictl/container.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/M, approved

#1633 crictl ps: output container namespace
  cmd/crictl/container.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/XS, approved

#1641 Fix panic if container metadata is `nil`
  cmd/crictl/container.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/XS, approved

#1642 Use golang context instead of `golang.org/x/net/context`
  cmd/crictl/pod_metrics.go
  cmd/crictl/pod_stats.go
  go.mod
Labels: cncf-cla: yes, lgtm, size/XS, kind/cleanup, approved

#1637 Allow prallel container removal
  cmd/crictl/container.go
  cmd/crictl/sandbox.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/M, approved

#1639 Allow parallel image removal
  cmd/crictl/image.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/M, approved

#1645 fix: fix validation error for go templates that use a crictl defined …
  cmd/crictl/templates.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/XS, approved

#1646 Add config file unit tests
  pkg/common/file.go
  pkg/common/file_test.go
  pkg/common/suite_test.go
Labels: cncf-cla: yes, lgtm, size/L, kind/cleanup, approved

#1648 Add more file based test cases
  pkg/common/file_test.go
Labels: cncf-cla: yes, lgtm, size/M, kind/cleanup, approved

#1657 Add warning log message about which config files to try
  pkg/common/config.go
Labels: cncf-cla: yes, lgtm, size/XS, kind/cleanup, approved

#1659 Add `crictl config` e2e tests
  test/e2e/config_test.go
Labels: cncf-cla: yes, lgtm, size/M, kind/cleanup, approved

#1660 Use const defines for config options
  cmd/crictl/config.go
  pkg/common/file.go
Labels: cncf-cla: yes, lgtm, size/M, kind/cleanup, approved

#1662 Clarify that `crictl config` without args refers to `set`
  cmd/crictl/config.go
Labels: cncf-cla: yes, lgtm, size/S, kind/documentation, approved

#1661 Fix `crictl config --set` if the YAML defines entries multiple times
  pkg/common/file.go
  test/e2e/config_test.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/M, approved
