Repository kubernetes-sigs/cri-tools, pull requests merged in 2024-04, with the labels that each got.

#1397 Add `criu` binary to CRI-O tests
  .github/workflows/crio.yml
Labels: cncf-cla: yes, lgtm, size/XS, kind/failing-test, approved

#1404 Update `release-notes` to v0.16.8
  hack/release-notes.sh
Labels: cncf-cla: yes, lgtm, size/XS, kind/cleanup, approved

#1400 Introduce new tests for new field Apparmor alongside the old ApparmorProfile
  pkg/validate/apparmor_linux.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/L, approved
