Repository kubernetes-sigs/cri-tools, pull requests merged in 2024-11, with the labels that each got.

#1667 Check and fix typos in CI
  .github/workflows/build.yml
  .typos.toml
  cmd/crictl/container.go
  cmd/crictl/image.go
  cmd/crictl/portforward.go
  cmd/crictl/util_test.go
  hack/release-notes.sh
  pkg/benchmark/util.go
  pkg/framework/test_context.go
  pkg/validate/apparmor_linux.go
  pkg/validate/idempotence.go
  pkg/validate/security_context_linux.go
  pkg/validate/selinux_linux.go
Labels: cncf-cla: yes, lgtm, size/M, kind/cleanup, approved

#1665 No need for overly strict criteria for judgment
  pkg/validate/multi_container_linux.go
Labels: cncf-cla: yes, lgtm, size/XS, kind/design, approved

#1668 Add TLS support for `crictl` `exec`, `portforward` and `attach`
  cmd/crictl/attach.go
  cmd/crictl/exec.go
  cmd/crictl/portforward.go
  cmd/crictl/util.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/L, approved

#1681 Use `slices.Compact` instead of own logic
  pkg/validate/image.go
Labels: cncf-cla: yes, lgtm, size/S, kind/cleanup, approved

#1682 Make `--tls-ca` optional
  cmd/crictl/exec.go
Labels: cncf-cla: yes, lgtm, size/XS, kind/cleanup, approved

#1683 Add `--profile-{cpu,mem}` flags
  .golangci.yml
  cmd/crictl/main.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/M, approved

#1686 bug fix: Fix panic if c.Image is nil
  cmd/crictl/container.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/XS, approved

#1685 Run prettier on supported files
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/dependabot.yml
  .github/workflows/build.yml
  .github/workflows/containerd.yml
  .github/workflows/crio.yml
  .github/workflows/release.yml
  .golangci.yml
  .prettierignore
  CHANGELOG.md
  docs/benchmark.md
  docs/crictl.1
  docs/crictl.md
  docs/developer-guide.md
  docs/examples/container-config.json
  docs/examples/container-config.yaml
  docs/examples/podsandbox-config.json
  images/cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, size/L, kind/cleanup, approved

#1674 add swap column to crictl stats
  cmd/crictl/container_stats.go
  cmd/crictl/display.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/XS, approved
