Repository kubernetes-sigs/cri-tools, pull requests merged in 2025-07, with the labels that each got.

#1868 Update golangci-lint and config
  .golangci.yml
  Makefile
  cmd/crictl/container.go
  cmd/crictl/container_stats.go
  cmd/crictl/events.go
  cmd/crictl/main.go
  cmd/crictl/pod_stats.go
  cmd/crictl/util.go
  cmd/critest/cri_test.go
  dependencies.yaml
  pkg/benchmark/util.go
  pkg/tracing/tracing.go
  pkg/validate/container.go
  pkg/validate/security_context_linux.go
  pkg/validate/streaming.go
Labels: cncf-cla: yes, lgtm, size/L, kind/cleanup, approved

#1862 Support websocket connections in `critest`
  cmd/crictl/attach.go
  cmd/crictl/exec.go
  cmd/crictl/portforward.go
  pkg/common/streaming.go
  pkg/framework/test_context.go
  pkg/validate/streaming.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/L, approved

#1872 add warning about empty cgroup_parent field in pod config
  cmd/crictl/util.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/XS, approved

#1874 support to auto generate pod uuid
  cmd/crictl/util.go
Labels: cncf-cla: yes, lgtm, size/XS, approved
