Repository kubernetes-sigs/cri-tools, pull requests merged in 2025-01, with the labels that each got.

#1742 Pass WindowsContainerResources in UpdateContainerResources call
  cmd/crictl/container.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/XS, approved

#1756 Fix `should not show help running rmi -a` e2e test
  test/e2e/inspect_test.go
Labels: cncf-cla: yes, lgtm, size/XS, kind/failing-test, approved

#1757 Update golangci-lint and config
  .golangci.yml
  Makefile
  dependencies.yaml
Labels: cncf-cla: yes, lgtm, size/XS, kind/cleanup, approved

#1759 Enable `wsl` and `nlreturn` linters
  .golangci.yml
  cmd/crictl/attach.go
  cmd/crictl/completion.go
  cmd/crictl/config.go
  cmd/crictl/container.go
  cmd/crictl/container_stats.go
  cmd/crictl/container_test.go
  cmd/crictl/display.go
  cmd/crictl/events.go
  cmd/crictl/exec.go
  cmd/crictl/image.go
  cmd/crictl/image_test.go
  cmd/crictl/info.go
  cmd/crictl/logs.go
  cmd/crictl/main.go
  cmd/crictl/pod_metrics.go
  cmd/crictl/pod_stats.go
  cmd/crictl/portforward.go
  cmd/crictl/sandbox.go
  cmd/crictl/templates.go
  cmd/crictl/templates_test.go
  cmd/crictl/update_runtime_config.go
  cmd/crictl/util.go
  cmd/crictl/util_test.go
  cmd/crictl/version.go
  cmd/critest/cri_test.go
  pkg/benchmark/pod_container.go
  pkg/benchmark/util.go
  pkg/common/config.go
  pkg/common/file.go
  pkg/common/file_test.go
  pkg/common/pod_config.go
  pkg/framework/framework.go
  pkg/framework/test_context.go
  pkg/framework/util.go
  pkg/tracing/tracing.go
  pkg/validate/apparmor_linux.go
  pkg/validate/container.go
  pkg/validate/container_linux.go
  pkg/validate/image.go
  pkg/validate/multi_container_linux.go
  pkg/validate/networking.go
  pkg/validate/pod.go
  pkg/validate/pod_linux.go
  pkg/validate/runtime_info.go
  pkg/validate/security_context_linux.go
  pkg/validate/selinux_linux.go
  pkg/validate/streaming.go
  test/e2e/config_test.go
  test/framework/framework.go
Labels: cncf-cla: yes, lgtm, size/XL, kind/cleanup, approved

#1761 fix the release status of critest
  docs/validation.md
Labels: cncf-cla: yes, lgtm, size/XS, kind/documentation, kind/cleanup, approved

#1760 Deflake e2e test `should not show help running rmi -a`
  test/e2e/inspect_test.go
  test/e2e/inspectp_test.go
  test/e2e/pull_test.go
  test/framework/framework.go
Labels: cncf-cla: yes, lgtm, size/M, kind/flake, approved
