Repository kubernetes-sigs/cri-tools, pull requests merged in 2025-02, with the labels that each got.

#1767 Rework the Makefile help
  Makefile
Labels: cncf-cla: yes, lgtm, size/L, kind/cleanup, approved

#1770 Use go-md2man v2
  docs/crictl.1
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  hack/verify-docs.sh
Labels: cncf-cla: yes, lgtm, size/XL, kind/documentation, approved

#1772 KEP-3619: Support RuntimeFeatures(.features) in "crictl info" command
  cmd/crictl/info.go
  cmd/crictl/util.go
  cmd/crictl/util_test.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/M, approved

#1782 Switch to go 1.24
  .github/workflows/build.yml
  .github/workflows/containerd.yml
  .github/workflows/crio.yml
  .github/workflows/release.yml
  .golangci.yml
  Makefile
  dependencies.yaml
  go.mod
Labels: cncf-cla: yes, lgtm, size/S, kind/cleanup, approved
