Repository kubernetes-sigs/cri-tools, pull requests merged in 2025-04, with the labels that each got.

#1823 Disable containerd hostport test
  .github/workflows/containerd.yml
Labels: cncf-cla: yes, lgtm, size/XS, kind/cleanup, approved

#1817 chore: add and migrate to sigs.k8s.io/yaml
  go.mod
  go.sum
  pkg/common/file.go
  pkg/framework/util.go
  vendor/modules.txt
  vendor/sigs.k8s.io/yaml/goyaml.v3/LICENSE
  vendor/sigs.k8s.io/yaml/goyaml.v3/NOTICE
  vendor/sigs.k8s.io/yaml/goyaml.v3/OWNERS
  vendor/sigs.k8s.io/yaml/goyaml.v3/README.md
  vendor/sigs.k8s.io/yaml/goyaml.v3/apic.go
  vendor/sigs.k8s.io/yaml/goyaml.v3/decode.go
  vendor/sigs.k8s.io/yaml/goyaml.v3/emitterc.go
  vendor/sigs.k8s.io/yaml/goyaml.v3/encode.go
  vendor/sigs.k8s.io/yaml/goyaml.v3/parserc.go
  vendor/sigs.k8s.io/yaml/goyaml.v3/patch.go
  vendor/sigs.k8s.io/yaml/goyaml.v3/readerc.go
  vendor/sigs.k8s.io/yaml/goyaml.v3/resolve.go
  vendor/sigs.k8s.io/yaml/goyaml.v3/scannerc.go
  vendor/sigs.k8s.io/yaml/goyaml.v3/sorter.go
  vendor/sigs.k8s.io/yaml/goyaml.v3/writerc.go
  vendor/sigs.k8s.io/yaml/goyaml.v3/yaml.go
  vendor/sigs.k8s.io/yaml/goyaml.v3/yamlh.go
  vendor/sigs.k8s.io/yaml/goyaml.v3/yamlprivateh.go
Labels: cncf-cla: yes, lgtm, size/XXL, kind/cleanup, approved, kind/deprecation

#1815 Add metricdescs subcommand for ListMetricDescriptors API
  cmd/crictl/main.go
  cmd/crictl/metric_descs.go
  docs/crictl.1
  docs/crictl.md
  test/e2e/metricdescs_test.go
  test/framework/framework.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/L, approved

#1819 pass down the context object wrapped within the urfave/cli.Context st…
  cmd/crictl/container.go
  cmd/crictl/events.go
  cmd/crictl/image.go
  cmd/crictl/info.go
  cmd/crictl/logs.go
  cmd/crictl/sandbox.go
  cmd/crictl/update_runtime_config.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#1812 fix the issue of regexp matching
  cmd/crictl/container.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1828 Update release notes tool to v0.18.0
  dependencies.yaml
  hack/release-notes.sh
Labels: cncf-cla: yes, lgtm, size/XS, kind/cleanup, approved

#1835 reuse urfave/cli.Context instead of creating a new instance
  cmd/crictl/container.go
  cmd/crictl/container_test.go
  cmd/crictl/exec.go
  cmd/crictl/image.go
  cmd/crictl/portforward.go
  cmd/crictl/runtime_config.go
  cmd/crictl/sandbox.go
  cmd/crictl/util.go
  cmd/crictl/version.go
Labels: cncf-cla: yes, lgtm, size/L, kind/cleanup, approved

#1834 add local imports to goimports formatting settings
  .golangci.yml
Labels: cncf-cla: yes, lgtm, size/XS, kind/cleanup, approved
