Repository kubernetes-sigs/cri-tools, pull requests merged in 2025-03, with the labels that each got.

#1781 Add `crictl update --oom-score-adj` flag
  cmd/crictl/container.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/XS, approved

#1793 Update cri-api to latest commit
  go.mod
  go.sum
  vendor/k8s.io/cri-api/pkg/apis/runtime/v1/api.pb.go
  vendor/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, size/XL, kind/cleanup, approved

#1794 Use go version requirements from go.mod
  .github/workflows/build.yml
  .github/workflows/containerd.yml
  .github/workflows/crio.yml
  .github/workflows/release.yml
  dependencies.yaml
Labels: cncf-cla: yes, lgtm, size/M, kind/cleanup, approved

#1805 bump cri-api to include API change
  go.mod
  go.sum
  vendor/k8s.io/cri-api/pkg/apis/runtime/v1/api.pb.go
  vendor/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto
  vendor/k8s.io/cri-api/pkg/apis/services.go
  vendor/k8s.io/cri-client/pkg/remote_runtime.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, size/XXL, kind/api-change, approved

#1803 Switch to golangci-lint v2
  .golangci.yml
  Makefile
  cmd/crictl/container.go
  cmd/crictl/container_stats.go
  cmd/crictl/events.go
  cmd/crictl/exec.go
  cmd/crictl/image.go
  cmd/crictl/info.go
  cmd/crictl/logs.go
  cmd/crictl/pod_stats.go
  cmd/crictl/portforward.go
  cmd/crictl/runtime_config.go
  cmd/crictl/sandbox.go
  cmd/crictl/update_runtime_config.go
  cmd/crictl/util.go
  cmd/crictl/version.go
  dependencies.yaml
  pkg/validate/security_context_linux.go
Labels: cncf-cla: yes, lgtm, size/L, kind/cleanup, approved
