Repository kubernetes-sigs/cri-tools, pull requests merged in 2025-06, with the labels that each got.

#1854 Revert "Disable containerd hostport test"
  .github/workflows/containerd.yml
Labels: cncf-cla: yes, lgtm, size/XS, kind/cleanup, approved

#1850 Add --all flag to crictl stop command.
  cmd/crictl/container.go
Labels: kind/feature, cncf-cla: yes, lgtm, size/M, approved

#1853 Fix regression in reading crictl config file
  pkg/common/config.go
Labels: kind/bug, cncf-cla: yes, lgtm, size/XS, approved
